import { StageInfo, GradeInfo, SubjectInfo, Lesson, Quiz, CountryInfo, CountryCode, StageType } from '@/types';

// ==========================================
// ARAB COUNTRIES CONFIGURATION
// ==========================================
export const ARAB_COUNTRIES: CountryInfo[] = [
  {
    code: 'eg',
    name: 'جمهورية مصر العربية',
    shortName: 'مصر',
    flag: '🇪🇬',
    academicYear: '2025/2026',
    vision: 'بناء أجيال مبدعة ومتمكنة علمياً تواكب أحدث منظومات التعليم الرقمي وتطوير المناهج لوزارة التربية والتعليم المصرية.',
    mission: 'تقديم شروحات مرئية تفاعلية ومراجعات ليلة الامتحان للشهادة الإعدادية والثانوية العامة وكافة الصفوف بالمنهج المصري.',
    examHighlight: 'امتحانات الثانوية العامة والشهادة الإعدادية',
    examTagline: 'بنك أسئلة ونماذج بوكليت تفاعلية وتدريبات بنك المعرفة المصري مع تصحيح وشرح فوري.',
    demonym: 'المصرية',
    description: 'شروحات المناهج المصرية لجميع المراحل التعليمية',
    activeCurriculumsCount: 12,
  },
  {
    code: 'sa',
    name: 'المملكة العربية السعودية',
    shortName: 'السعودية',
    flag: '🇸🇦',
    academicYear: '1447/1448هـ',
    vision: 'أن نكون المرجع والوجهة التعليمية الأولى في المملكة العربية السعودية مساهمين في تحقيق مستهدفات رؤية السعودية 2030.',
    mission: 'تيسير وتبسيط المفاهيم العلمية المعقدة في المناهج السعودية عبر شروحات مرئية وحلول نموذجية تواكب متطلبات الاختبارات الوطنية.',
    examHighlight: 'اختبارات نافس والتحصيلي والقدرات',
    examTagline: 'اختبر معلوماتك في دروس ومقررات المناهج السعودية، واحصل على تصحيح فوري وشرح الحلول النموذجية.',
    demonym: 'السعودية',
    description: 'شروحات المناهج السعودية لكافة الصفوف والمسارات',
    activeCurriculumsCount: 12,
  },
  {
    code: 'ae',
    name: 'الإمارات العربية المتحدة',
    shortName: 'الإمارات',
    flag: '🇦🇪',
    academicYear: '2025/2026',
    vision: 'دعم مسيرة التعليم المبتكر ومئوية الإمارات 2071 من خلال توفير شروحات رقمية متطورة لكافة المراحل التعليمية.',
    mission: 'تقديم محتوى تعليمي مرئي متميز للمناهج الوزارية ومدارس الإمارات يركز على مهارات التفكير والابتكار.',
    examHighlight: 'اختبارات إمسات (EmSAT) والتقويم الوزاري',
    examTagline: 'تدريبات وبنوك أسئلة تفاعلية تحاكي اختبارات الإمارات القياسية إمسات وتقييمات وزارة التربية والتعليم.',
    demonym: 'الإماراتية',
    description: 'شروحات المنهاج الإماراتي لمختلف الحلقات الدراسية',
    activeCurriculumsCount: 12,
  },
  {
    code: 'kw',
    name: 'دولة الكويت',
    shortName: 'الكويت',
    flag: '🇰🇼',
    academicYear: '2025/2026',
    vision: 'الارتقاء بالمنظومة التعليمية الرقمية ومساندة أبنائنا الطلبة في دولة الكويت للتفوق الأكاديمي الشامل.',
    mission: 'توفير شروحات مبسطة واختبارات تفاعلية ومذكرات مراجعة للمناهج الكويتية للمرحلة الابتدائية والمتوسطة والثانوية.',
    examHighlight: 'امتحانات الفترة ونهاية العام للثانوية العامة',
    examTagline: 'مذكرات واختبارات تدريبية شاملة لنماذج امتحانات وزارة التربية الكويتية مع حلول نموذجية.',
    demonym: 'الكويتية',
    description: 'المناهج الدراسية الكويتية لكافة المراحل',
    activeCurriculumsCount: 12,
  },
  {
    code: 'jo',
    name: 'المملكة الأردنية الهاشمية',
    shortName: 'الأردن',
    flag: '🇯🇴',
    academicYear: '2025/2026',
    vision: 'تمكين الطالب الأردني من الوصول لأعلى درجات التميز في امتحانات الثانوية العامة (التوجيهي) وكافة الصفوف.',
    mission: 'شروحات وافية ومكثفات دراسية للمنهاج الأردني تغطي كافة المواد العلمية والأدبية.',
    examHighlight: 'امتحان شهادة الدراسة الثانوية العامة (التوجيهي)',
    examTagline: 'أسئلة سنوات سابقة وامتحانات تجريبية لشهادة التوجيهي الأردني مع الشرح التفصيلي للحل.',
    demonym: 'الأردنية',
    description: 'شروحات المنهاج الأردني والتوجيهي',
    activeCurriculumsCount: 12,
  },
  {
    code: 'qa',
    name: 'دولة قطر',
    shortName: 'قطر',
    flag: '🇶🇦',
    academicYear: '2025/2026',
    vision: 'مواكبة رؤية قطر الوطنية 2030 في تطوير مخرجات التعليم وتوفير منصة تعليمية رقمية رائدة.',
    mission: 'تيسير المناهج التعليمية لمعايير وزارة التربية والتعليم والتعليم العالي القطرية عبر شروحات نوعية.',
    examHighlight: 'اختبارات نهاية الفصل والشهادة الثانوية العامة',
    examTagline: 'نماذج اختبارات تقييمية مطابقة لمعايير التقييم التربوي الشامل في دولة قطر.',
    demonym: 'القطرية',
    description: 'المناهج القطرية لمختلف المراحل الدراسية',
    activeCurriculumsCount: 12,
  },
  {
    code: 'om',
    name: 'سلطنة عُمان',
    shortName: 'عُمان',
    flag: '🇴🇲',
    academicYear: '2025/2026',
    vision: 'المساهمة في تحقيق أولويات رؤية عُمان 2040 عبر تعزيز التعليم الإلكتروني التفاعلي وجودة التعلم.',
    mission: 'شرح المناهج العمانية لمراحل التعليم الأساسي وما بعد الأساسي واختبارات دبلوم التعليم العام.',
    examHighlight: 'امتحانات دبلوم التعليم العام والتقويم المستمر',
    examTagline: 'اختبارات تدريبية ومراجعات شاملة لشهادة دبلوم التعليم العام لوزارة التربية والتعليم العمانية.',
    demonym: 'العُمانية',
    description: 'مناهج سلطنة عمان والتعليم الأساسي',
    activeCurriculumsCount: 12,
  },
  {
    code: 'general',
    name: 'المنهج العربي الموحد (شامل)',
    shortName: 'عام',
    flag: '🌐',
    academicYear: '2025/2026',
    vision: 'منصة تعليمية عربية موحدة تجمع أفضل الشروحات العلمية لكافة الطلاب في العالم العربي.',
    mission: 'تبسيط العلوم والرياضيات واللغات من خلال أحدث الأساليب البيداغوجية والتقنيات الرقمية.',
    examHighlight: 'الاختبارات الدولية والمهارات التأسيسية',
    examTagline: 'اختبارات تقييمية في العلوم والرياضيات واللغة العربية تغطي المهارات الأساسية لكل المراحل.',
    demonym: 'العربية',
    description: 'محتوى تعليمي شامل لكافة الطلاب في الوطن العربي',
    activeCurriculumsCount: 12,
  },
];

export function getCountryInfo(code: CountryCode = 'eg'): CountryInfo {
  return ARAB_COUNTRIES.find(c => c.code === code) || ARAB_COUNTRIES[0];
}

// ==========================================
// STAGES CONFIGURATION
// ==========================================
export const STAGES: StageInfo[] = [
  {
    id: 'elementary',
    name: 'المرحلة الابتدائية',
    description: 'الصفوف من الأول إلى السادس الابتدائي',
    iconName: 'School',
    color: 'from-amber-500 to-yellow-600',
    gradesCount: 6,
    country: 'sa',
  },
  {
    id: 'middle',
    name: 'المرحلة المتوسطة',
    description: 'الصفوف من الأول إلى الثالث المتوسط',
    iconName: 'BookOpen',
    color: 'from-emerald-600 to-teal-700',
    gradesCount: 3,
    country: 'sa',
  },
  {
    id: 'secondary',
    name: 'المرحلة الثانوية (مسارات)',
    description: 'السنة الأولى المشتركة ومسارات التخصص',
    iconName: 'GraduationCap',
    color: 'from-blue-600 to-indigo-700',
    gradesCount: 3,
    country: 'sa',
  },
  {
    id: 'elementary',
    name: 'المرحلة الابتدائية',
    description: 'الصفوف من الأول إلى السادس الابتدائي • المنهج الجديد',
    iconName: 'School',
    color: 'from-amber-500 to-yellow-600',
    gradesCount: 6,
    country: 'eg',
  },
  {
    id: 'middle',
    name: 'المرحلة الإعدادية',
    description: 'صفوف أولى وتانية وتالتة إعدادي • الشهادة الإعدادية',
    iconName: 'BookOpen',
    color: 'from-emerald-600 to-teal-700',
    gradesCount: 3,
    country: 'eg',
  },
  {
    id: 'secondary',
    name: 'المرحلة الثانوية (الثانوية العامة)',
    description: 'صفوف أولى وتانية وتالتة ثانوي • النظام الجديد',
    iconName: 'GraduationCap',
    color: 'from-blue-600 to-indigo-700',
    gradesCount: 3,
    country: 'eg',
  },
];

export function getStagesForCountry(country: CountryCode = 'eg'): StageInfo[] {
  let list = STAGES.filter(s => s.country === country);
  if (list.length === 0) {
    list = STAGES.filter(s => s.country === 'sa');
  }
  return list;
}

// ==========================================
// GRADES CONFIGURATION
// ==========================================
export const GRADES: GradeInfo[] = [
  { id: 'elem-1', name: 'الصف الأول الابتدائي', stage: 'elementary', gradeNumber: 1, stageNameAr: 'الابتدائي', description: 'تأسيس القراءة والكتابة والرياضيات', iconName: 'Sparkles', country: 'sa' },
  { id: 'elem-2', name: 'الصف الثاني الابتدائي', stage: 'elementary', gradeNumber: 2, stageNameAr: 'الابتدائي', description: 'العمليات الحسابية والعلوم الأساسية', iconName: 'Star', country: 'sa' },
  { id: 'elem-3', name: 'الصف الثالث الابتدائي', stage: 'elementary', gradeNumber: 3, stageNameAr: 'الابتدائي', description: 'توسيع المدارك والقراءة التفاعلية', iconName: 'Compass', country: 'sa' },
  { id: 'elem-4', name: 'الصف الرابع الابتدائي', stage: 'elementary', gradeNumber: 4, stageNameAr: 'الابتدائي', description: 'مناهج العلوم والرياضيات والاجتماعيات', iconName: 'Award', country: 'sa' },
  { id: 'elem-5', name: 'الصف الخامس الابتدائي', stage: 'elementary', gradeNumber: 5, stageNameAr: 'الابتدائي', description: 'الكسور والعمليات المتقدمة', iconName: 'Award', country: 'sa' },
  { id: 'elem-6', name: 'الصف السادس الابتدائي', stage: 'elementary', gradeNumber: 6, stageNameAr: 'الابتدائي', description: 'التحضير للمرحلة المتوسطة ومسابقات الموهوبين', iconName: 'Award', country: 'sa' },

  { id: 'mid-1', name: 'الصف الأول المتوسط', stage: 'middle', gradeNumber: 1, stageNameAr: 'المتوسط', description: 'الجبر والدوال والعلوم العامة', iconName: 'GraduationCap', country: 'sa' },
  { id: 'mid-2', name: 'الصف الثاني المتوسط', stage: 'middle', gradeNumber: 2, stageNameAr: 'المتوسط', description: 'الأعداد النسبية والدولة الأموية وحركة المادة', iconName: 'GraduationCap', country: 'sa' },
  { id: 'mid-3', name: 'الصف الثالث المتوسط', stage: 'middle', gradeNumber: 3, stageNameAr: 'المتوسط', description: 'التحضير للاختبارات الوطنية واختبار نافس', iconName: 'Trophy', country: 'sa' },

  { id: 'sec-1', name: 'السنة الأولى المشتركة', stage: 'secondary', gradeNumber: 1, stageNameAr: 'الثانوي', description: 'مسارات الثانوي المشترك والمواد العامة', iconName: 'Atom', country: 'sa' },
  { id: 'sec-2', name: 'الصف الثاني الثانوي', stage: 'secondary', gradeNumber: 2, stageNameAr: 'الثانوي', description: 'مسار عام، صحة، حاسب، وإدارة أعمال', iconName: 'Cpu', country: 'sa' },
  { id: 'sec-3', name: 'الصف الثالث الثانوي', stage: 'secondary', gradeNumber: 3, stageNameAr: 'الثانوي', description: 'التخرج والتحضير للقدرات والتحصيلي', iconName: 'Sparkles', country: 'sa' },

  { id: 'eg-elem-1', name: 'الصف الأول الابتدائي', stage: 'elementary', gradeNumber: 1, stageNameAr: 'الابتدائي', description: 'المنهج المطور 2.0 واللغة العربية والحساب', iconName: 'Sparkles', country: 'eg' },
  { id: 'eg-elem-2', name: 'الصف الثاني الابتدائي', stage: 'elementary', gradeNumber: 2, stageNameAr: 'الابتدائي', description: 'العمليات الحسابية والقصص القرائية', iconName: 'Star', country: 'eg' },
  { id: 'eg-elem-3', name: 'الصف الثالث الابتدائي', stage: 'elementary', gradeNumber: 3, stageNameAr: 'الابتدائي', description: 'جداول الضرب وأساليب وتراكيب اللغة', iconName: 'Compass', country: 'eg' },
  { id: 'eg-elem-4', name: 'الصف الرابع الابتدائي', stage: 'elementary', gradeNumber: 4, stageNameAr: 'الابتدائي', description: 'الرياضيات والعلوم والدراسات الاجتماعية المطورة', iconName: 'Award', country: 'eg' },
  { id: 'eg-elem-5', name: 'الصف الخامس الابتدائي', stage: 'elementary', gradeNumber: 5, stageNameAr: 'الابتدائي', description: 'الرياضيات والعلوم والدراسات الاجتماعية', iconName: 'Compass', country: 'eg' },
  { id: 'eg-elem-6', name: 'الصف السادس الابتدائي', stage: 'elementary', gradeNumber: 6, stageNameAr: 'الابتدائي', description: 'الشهادة الابتدائية والمفاهيم التأسيسية', iconName: 'Award', country: 'eg' },

  { id: 'eg-mid-1', name: 'الصف الأول الإعدادي', stage: 'middle', gradeNumber: 1, stageNameAr: 'الإعدادي', description: 'الجبر والهندسة، العلوم، الدراسات الاجتماعية', iconName: 'GraduationCap', country: 'eg' },
  { id: 'eg-mid-2', name: 'الصف الثاني الإعدادي', stage: 'middle', gradeNumber: 2, stageNameAr: 'الإعدادي', description: 'الرياضيات والعلوم واللغة العربية', iconName: 'GraduationCap', country: 'eg' },
  { id: 'eg-mid-3', name: 'الصف الثالث الإعدادي (الشهادة الإعدادية)', stage: 'middle', gradeNumber: 3, stageNameAr: 'الإعدادي', description: 'المراجعات النهائية والامتحانات النموذجية', iconName: 'Trophy', country: 'eg' },

  { id: 'eg-sec-1', name: 'الصف الأول الثانوي', stage: 'secondary', gradeNumber: 1, stageNameAr: 'الثانوي', description: 'الفيزياء، الكيمياء، الأحياء، والرياضيات', iconName: 'Atom', country: 'eg' },
  { id: 'eg-sec-2', name: 'الصف الثاني الثانوي', stage: 'secondary', gradeNumber: 2, stageNameAr: 'الثانوي', description: 'الشعبة العلمية والشعبة الأدبية', iconName: 'Cpu', country: 'eg' },
  { id: 'eg-sec-3', name: 'الصف الثالث الثانوي (الثانوية العامة)', stage: 'secondary', gradeNumber: 3, stageNameAr: 'الثانوي', description: 'تجهيزات الثانوية العامة ونماذج الامتحانات الرسمية', iconName: 'Sparkles', country: 'eg' },
];

export function getGradesForCountry(country: CountryCode = 'eg', stage?: StageType) {
  let countryGrades = GRADES.filter(g => g.country === country);
  if (countryGrades.length === 0) {
    countryGrades = GRADES.filter(g => g.country === 'sa');
  }
  if (stage) {
    return countryGrades.filter(g => g.stage === stage);
  }
  return countryGrades;
}

// ==========================================
// SUBJECTS CONFIGURATION
// ==========================================
export const SUBJECTS: SubjectInfo[] = [
  { id: 'math-elem', name: 'الرياضيات', code: 'MATH', stage: 'elementary', grades: [1, 2, 3, 4, 5, 6], color: 'from-blue-600 to-indigo-700', iconName: 'Calculator', description: 'الأعداد، العمليات الحسابية، القياس، وحل المسائل', country: 'sa' },
  { id: 'social-elem', name: 'الدراسات الاجتماعية', code: 'SOC', stage: 'elementary', grades: [4, 5, 6], color: 'from-amber-600 to-yellow-700', iconName: 'Globe2', description: 'الهوية الوطنية، التاريخ، والجغرافيا', country: 'sa' },
  { id: 'science-elem', name: 'العلوم', code: 'SCI', stage: 'elementary', grades: [1, 2, 3, 4, 5, 6], color: 'from-emerald-600 to-teal-700', iconName: 'FlaskConical', description: 'المخلوقات الحية والمادة والطاقة', country: 'sa' },
  { id: 'arabic-elem', name: 'لغتي الجميلة', code: 'ARB', stage: 'elementary', grades: [1, 2, 3, 4, 5, 6], color: 'from-rose-600 to-pink-700', iconName: 'BookA', description: 'القراءة والكتابة وقواعد اللغة العربية', country: 'sa' },

  { id: 'math-mid', name: 'الرياضيات', code: 'MATH', stage: 'middle', grades: [1, 2, 3], color: 'from-blue-600 to-indigo-700', iconName: 'Calculator', description: 'الأعداد النسبية، القوى والأسس، الجبر، والهندسة', country: 'sa' },
  { id: 'social-mid', name: 'الدراسات الاجتماعية', code: 'SOC', stage: 'middle', grades: [1, 2, 3], color: 'from-amber-600 to-yellow-700', iconName: 'Globe2', description: 'التاريخ والجغرافيا والدراسات الاجتماعية', country: 'sa' },
  { id: 'science-mid', name: 'العلوم', code: 'SCI', stage: 'middle', grades: [1, 2, 3], color: 'from-emerald-600 to-teal-700', iconName: 'FlaskConical', description: 'طبيعة المادة، القوى، والحركة', country: 'sa' },
  { id: 'arabic-mid', name: 'لغتي الخالدة', code: 'ARB', stage: 'middle', grades: [1, 2, 3], color: 'from-rose-600 to-pink-700', iconName: 'BookA', description: 'النحو والصرف والبلاغة', country: 'sa' },

  { id: 'physics-sec', name: 'الفيزياء', code: 'PHYS', stage: 'secondary', grades: [1, 2, 3], color: 'from-sky-600 to-blue-800', iconName: 'Atom', description: 'حركة الكواكب والجاذبية، الميكانيكا، والكهرباء', country: 'sa' },
  { id: 'bio-sec', name: 'الأحياء', code: 'BIO', stage: 'secondary', grades: [1, 2, 3], color: 'from-emerald-600 to-green-700', iconName: 'Dna', description: 'خصائص شوكيات الجلد، الحيوانات اللافقارية، والخلية', country: 'sa' },
  { id: 'chem-sec', name: 'الكيمياء', code: 'CHEM', stage: 'secondary', grades: [1, 2, 3], color: 'from-teal-600 to-emerald-800', iconName: 'FlaskConical', description: 'المادة وتغيراتها والحسابات الكيميائية', country: 'sa' },
  { id: 'math-sec', name: 'الرياضيات (مسارات)', code: 'MATH', stage: 'secondary', grades: [1, 2, 3], color: 'from-blue-600 to-indigo-700', iconName: 'Calculator', description: 'الدوال، المصفوفات، والتفاضل والتكامل', country: 'sa' },

  { id: 'eg-math-mid', name: 'الجبر والهندسة', code: 'MATH', stage: 'middle', grades: [1, 2, 3], color: 'from-blue-600 to-indigo-700', iconName: 'Calculator', description: 'الجبر والإحصاء، الهندسة المستوية والتحليلية وحساب المثلثات', country: 'eg' },
  { id: 'eg-science-mid', name: 'العلوم العامة', code: 'SCI', stage: 'middle', grades: [1, 2, 3], color: 'from-emerald-600 to-teal-700', iconName: 'FlaskConical', description: 'المادة وتركيبها، التفاعلات الكيميائية، والوراثة والكون', country: 'eg' },
  { id: 'eg-social-mid', name: 'الدراسات الاجتماعية', code: 'SOC', stage: 'middle', grades: [1, 2, 3], color: 'from-amber-600 to-yellow-700', iconName: 'Globe2', description: 'جغرافيا العالم وتاريخ مصر عبر العصور', country: 'eg' },
  { id: 'eg-arabic-mid', name: 'اللغة العربية والنحو', code: 'ARB', stage: 'middle', grades: [1, 2, 3], color: 'from-rose-600 to-pink-700', iconName: 'BookA', description: 'النصوص والقراءة وقواعد النحو والإعراب', country: 'eg' },
  { id: 'eg-physics-sec', name: 'الفيزياء (ثانوية عامة)', code: 'PHYS', stage: 'secondary', grades: [1, 2, 3], color: 'from-sky-600 to-blue-800', iconName: 'Atom', description: 'التيار الكهربي وقانون أوم، الكهرومغناطيسية، والفيزياء الحديثة', country: 'eg' },
  { id: 'eg-chem-sec', name: 'الكيمياء (ثانوية عامة)', code: 'CHEM', stage: 'secondary', grades: [1, 2, 3], color: 'from-teal-600 to-emerald-800', iconName: 'FlaskConical', description: 'العناصر الانتقالية، التحليل الكيميائي، والاتزان والكيمياء العضوية', country: 'eg' },
  { id: 'eg-bio-sec', name: 'الأحياء (ثانوية عامة)', code: 'BIO', stage: 'secondary', grades: [1, 2, 3], color: 'from-emerald-600 to-green-700', iconName: 'Dna', description: 'الدعامة والحركة، التنسيق الهرموني، التكاثر، والبيولوجيا الجزيئية', country: 'eg' },
];

export function getSubjectsForCountry(country: CountryCode = 'eg', stage?: StageType, gradeNumber?: number) {
  let list = SUBJECTS.filter(s => s.country === country);
  if (list.length === 0) {
    list = SUBJECTS.filter(s => s.country === 'sa');
  }
  if (stage) {
    list = list.filter(s => s.stage === stage);
  }
  if (gradeNumber) {
    list = list.filter(s => s.grades.includes(gradeNumber));
  }
  return list;
}

// ==========================================
// INITIAL LESSONS (Accurately classified from channel videos)
// ==========================================
export const INITIAL_LESSONS: Lesson[] = [
  {
    "id": "yt_c07xaKcQG0g",
    "title": "مراجعة المكتسبات الماضية | لغتي الجميلة سادس ابتدائي | الفصل الأول 1448هـ",
    "description": "📚 مراجعة المكتسبات الماضية | لغتي الجميلة للصف السادس الابتدائي | الفصل الدراسي الأول 1448هـ\n\nفي هذا الفيديو من منصة الهَدَّاف التعليمية نقدم شرحًا ومراجعة مبسطة لدرس مراجعة المكتسبات الماضية في مادة لغتي الجميلة للصف السادس الابتدائي، وفق المنهج السعودي 1448هـ.\n\n🎯 ماذا سنتعلم في هذا الدرس؟\n• مراجعة أهم المكتسبات والمهارات اللغوية السابقة.\n• استرجاع المعلومات والمعارف التي سبق تعلمها.\n• مراجعة المهارات اللغوية المهمة للصف السادس الابتدائي.\n• تطبيق المهارات من خلال أمثلة وتدريبات متنوعة.\n• الاستعداد لدروس ومهارات الفصل الدراسي الأول.\n• تثبيت المعلومات بطريقة سهلة ومبسطة تساعد على الفهم والمراجعة.\n\n🎓 الفيديو مناسب لجميع طلاب وطالبات الصف السادس الابتدائي الراغبين في فهم ومراجعة مادة لغتي الجميلة والاستعداد للدروس والاختبارات.\n\n🇸🇦 المادة: لغتي الجميلة\n📖 الصف: السادس الابتدائي\n📅 الفصل الدراسي: الأول\n📚 المنهج: السعودي 1448هـ\n📝 الدرس: مراجعة المكتسبات الماضية\n\n🌐 منصة الهداف التعليمية:\nhttps://alhadaf-edu.vercel.app\n\n🏆 أبطال الهداف على التيليجرام:\nhttps://t.me/alhadaaf_edu\n\n📢 قناة الهداف على التيليجرام:\nhttps://t.me/alhadaf_edu\n\n⭐ لا تنسَ الاشتراك في قناة الهداف التعليمية وتفعيل 🔔 الجرس ليصلك كل جديد من شروحات ومراجعات المنهج السعودي.\n\n🔥 الهاشتاجات\n\n#لغتي_الجميلة #لغتي_سادس_ابتدائي #سادس_ابتدائي #مراجعة_المكتسبات_الماضية #مراجعة_المكتسبات #لغتي #المنهج_السعودي #الفصل_الدراسي_الأول #1448هـ #شرح_لغتي #علوم_تعليمية #الهداف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 6,
    "subjectId": "arabic-elem",
    "subjectName": "لغتي الجميلة",
    "term": 1,
    "unitTitle": "مراجعة المكتسبات الماضية",
    "youtubeId": "c07xaKcQG0g",
    "youtubeUrl": "https://www.youtube.com/watch?v=c07xaKcQG0g",
    "thumbnailUrl": "https://i.ytimg.com/vi/c07xaKcQG0g/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1500,
    "likesCount": 150,
    "createdAt": "2026-09-03T22:48:36Z"
  },
  {
    "id": "yt_Sz0-Hq4L6lM",
    "title": "شرح مراجعة المكتسبات السابقة لغتي الصف الرابع الابتدائي الفصل الدراسي الأول 1448هـ | المنهاج السعودي",
    "description": "شرح تفصيلي ومبسط لدرس مراجعة المكتسبات السابقة في مادة لغتي للصف الرابع الابتدائي (الفصل الدراسي الأول) وفق المنهج السعودي لعام 1448هـ. نستعرض في هذا الفيديو أهم المهارات والقواعد السابقة لضمان انطلاقة قوية ومميزة لأبطال الصف الرا��ع.\n\n🌐 منصة الهداف التعليمية:\nhttps://alhadaf-edu.vercel.app\n\nأبطال الهداف على التيليجرام:\nhttps://t.me/alhadaaf_edu\n\nقناة الهداف على التيليجرام:\nhttps://t.me/alhadaf_edu\n\nلا تنسوا الإعجاب بالفيديو والاشتراك في القناة ليصلكم كل جديد ومفيد لمرحلتكم الدراسية.\n\n# الهاشتاجات\n#لغتي_الصف_الرابع #مراجعة_المكتسبات_السابقة #المنهج_السعودي #الفصل_الدراسي_الأول #الصف_الرابع_الابتدائي #منصة_الهداف_التعليمية",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "arabic-elem",
    "subjectName": "لغتي الجميلة",
    "term": 1,
    "unitTitle": "شرح مراجعة المكتسبات السابقة لغتي الصف الرابع الابتدائي الفصل الدراسي الأول 1448هـ",
    "youtubeId": "Sz0-Hq4L6lM",
    "youtubeUrl": "https://www.youtube.com/watch?v=Sz0-Hq4L6lM",
    "thumbnailUrl": "https://i.ytimg.com/vi/Sz0-Hq4L6lM/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1480,
    "likesCount": 148,
    "createdAt": "2026-09-03T21:59:21Z"
  },
  {
    "id": "yt_YDr_H-qFPzU",
    "title": "شرح الحيوانات اللافقارية | علوم رابع ابتدائي الفصل الدراسي الأول 1448هـ | الدرس الأول |الفصل الثانى",
    "description": "🦋 شرح الحيوانات اللافقارية | علوم رابع ابتدائي الفصل الدراسي الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو من **منصة الهَدَّاف التعليمية** نقدم شرحًا مبسطًا وممتعًا لدرس **الحيوانات اللافقارية** في مادة العلوم للصف الرابع الابتدائي، وفق **المنهج السعودي 1448هـ**.\n\n🎯 في هذا الدرس سنتعرف على:\n• ما المقصود بالحيوانات اللافقارية؟\n• ما أهم خصائص الحيوانات اللافقارية؟\n• أنواع الحيوانات اللافقارية.\n• أمثلة على الحيوانات اللافقارية.\n• كيفية تصنيف الحيوانات اللافقارية.\n• أهم الفروق بين الحيوانات الفقارية واللافقارية.\n• أمثلة وتوضيحات تساعد على فهم الدرس وتثبيت المعلومات.\n\n🎓 تابع سلسلة علوم رابع ابتدائي على قناة الهداف التعليمية، واستعد للاختبارات بطريقة سهلة وممتعة.\nhttps://www.youtube.com/playlist?list=PLLBCQc0XbSL8\n📚 الفيديو مناسب لطلاب وطالبات **الصف الرابع الابتدائي – مادة العلوم – الفصل الدراسي الأول**.\n\n🌐 **منصة الهداف التعليمية:**\nhttps://alhadaf-edu.vercel.app\n\n🏆 **أبطال الهداف على التيليجرام:**\nhttps://t.me/alhadaaf_edu\n\n📢 **قناة الهداف على التيليجرام:**\nhttps://t.me/alhadaf_edu\n\n⭐ إذا أعجبك الشرح، لا تنسَ الاشتراك في القناة وتفعيل 🔔 الجرس ليصلك كل جديد من دروس العلوم والمواد التعليمية.\n\n#الهَدَّاف #علوم_رابع_ابتدائي #الحيوانات_اللافقارية #علوم #رابع_ابتدائي #الفصل_الدراسي_الأول #المنهج_السعودي #علوم_رابع #شرح_علوم",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "شرح الحيوانات اللافقارية",
    "youtubeId": "YDr_H-qFPzU",
    "youtubeUrl": "https://www.youtube.com/watch?v=YDr_H-qFPzU",
    "thumbnailUrl": "https://i.ytimg.com/vi/YDr_H-qFPzU/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1460,
    "likesCount": 146,
    "createdAt": "2026-09-03T21:09:44Z"
  },
  {
    "id": "yt_A-4PtVE_tE8",
    "title": "تكملة درس الضوء وطاقة الكم | كيمياء ثاني ثانوي | الفصل الأول 1448هـ | شرح مبسط",
    "description": "🧪 تكملة شرح درس الضوء وطاقة الكم | كيمياء الصف الثاني الثانوي | الفصل الدراسي الأول 1448هـ\n\nفي هذا الفيديو نكمل معًا شرح درس الضوء وطاقة الكم في مادة الكيمياء للصف الثاني الثانوي، بطريقة مبسطة ومنظمة تساعدك على فهم الدرس واستيعاب أهم المفاهيم والنقاط المهمة في المنهج.\n\n📚 ماذا ستتعلم في هذا الفيديو؟\n✅ تكملة شرح درس الضوء وطاقة الكم\n✅ أهم المفاهيم والقوانين المتعلقة بالدرس\n✅ تبسيط الأفكار الكيميائية بطريقة سهلة\n✅ أمثلة وتوضيحات تساعد على تثبيت المعلومات\n✅ مراجعة أهم النقاط التي يحتاجها الطالب\n\n🎓 الفيديو مناسب لطلاب الصف الثاني الثانوي وفق منهج الكيمياء السعودي – الفصل الدراسي الأول 1448هـ.\n\n⭐ تابع الدرس للنهاية، واشترك في القناة وفعل 🔔 التنبيهات ليصلك كل جديد من دروس ومراجعات الهَدَّاف التعليمية.\n\n━━━━━━━━━━━━━━━\n🌐 منصة الهداف التعليمية:\nhttps://alhadaf-edu.vercel.app\n\n📱 أبطال الهداف على التيليجرام:\nhttps://t.me/alhadaaf_edu\n\n📢 قناة الهداف على التيليجرام:\nhttps://t.me/alhadaf_edu\n━━━━━━━━━━━━━━━\n\n#كيمياء #ثاني_ثانوي #الضوء_وطاقة_الكم #كيمياء_ثاني_ثانوي #كيمياء_1448 #منهج_السعودية #الهداف_التعليمية #تعليم_السعودية",
    "country": "sa",
    "stage": "secondary",
    "gradeNumber": 2,
    "subjectId": "chem-sec",
    "subjectName": "الكيمياء",
    "term": 1,
    "unitTitle": "تكملة درس الضوء وطاقة الكم",
    "youtubeId": "A-4PtVE_tE8",
    "youtubeUrl": "https://www.youtube.com/watch?v=A-4PtVE_tE8",
    "thumbnailUrl": "https://i.ytimg.com/vi/A-4PtVE_tE8/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1440,
    "likesCount": 144,
    "createdAt": "2026-09-03T09:30:41Z"
  },
  {
    "id": "yt_xw9DS1g7dCI",
    "title": "تصنيف المخلوقات الحية | علوم رابع ابتدائي الفصل الأول 1448هـ | شرح الدرس الثاني كامل",
    "description": "🔬 تصنيف المخلوقات الحية | علوم رابع ابتدائي | الفصل الأول 1448هـ\n\nفي هذا الفيديو نقدم لكم شرح الدرس الثاني: تصنيف المخلوقات الحية من مادة العلوم للصف الرابع الابتدائي، الفصل الدراسي الأول 1448هـ، بطريقة سهلة ومبسطة تساعد الطلاب على فهم الدرس والاستعداد للاختبارات.\n\n📚 سنتعرف في الدرس على:\n✅ مفهوم تصنيف المخلوقات الحية\n✅ كيفية تصنيف الكائنات والمخلوقات الحية\n✅ المجموعات والتصنيف\n✅ أهم المفاهيم والمصطلحات في الدرس\n✅ أمثلة وتطبيقات تساعد على فهم الدرس\n✅ مراجعة أهم الأسئلة والتدريبات\n\n🎯 شرح مبسط + أمثلة + مراجعة + أسئلة لمساعدة طلاب الصف الرابع الابتدائي على المذاكرة وتحقيق أفضل النتائج.\n\n🌐 منصة الهداف التعليمية:\nhttps://alhadaf-edu.vercel.app\n أبطال الهداف على التيليجرام:\n https://t.me/alhadaaf_edu \nقناة الهداف على التيليجرام :\nhttps://t.me/alhadaf_edu\n\n📺 تابع قناة الهداف التعليمية لمزيد من شروحات ومراجعات منهج العلوم والمواد الدراسية.\n\n👍 اشترك في القناة وفعل 🔔 الجرس ليصلك كل جديد.\n\n🏷️ هاشتاجات\n#تصنيف_المخلوقات_الحية #علوم_رابع_ابتدائي #علوم_رابع #رابع_ابتدائي #شرح_العلوم #الدرس_الثاني #الفصل_الأول #علوم_1448 #منهج_السعودية #الهداف_التعليمية",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "تصنيف المخلوقات الحية",
    "youtubeId": "xw9DS1g7dCI",
    "youtubeUrl": "https://www.youtube.com/watch?v=xw9DS1g7dCI",
    "thumbnailUrl": "https://i.ytimg.com/vi/xw9DS1g7dCI/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1420,
    "likesCount": 142,
    "createdAt": "2026-09-03T08:33:05Z"
  },
  {
    "id": "yt_hTb8Li2JvIc",
    "title": "الخلايا | علوم رابع ابتدائي الفصل الأول 1448هـ | تكملة شرح الدرس الأول كاملة | شرح مبسط",
    "description": "🔬 شرح درس الخلايا – علوم رابع ابتدائي – الفصل الدراسي الأول 1448هـ\n\nفي هذا الفيديو نكمل معكم شرح الدرس الأول: الخلايا م�� مادة العلوم للصف الرابع الابتدائي، ضمن الفصل الأول ممالك المخلوقات الحية، بطريقة سهلة ومبسطة تساعد الطالب على فهم الدرس والاستعداد للاختبارات.\n\n📚 هذا الفيديو هو تكملة للشرح السابق لدرس الخلايا:\nشاهد الجزء الأول من شرح الخلايا\n\n🧬 في الشرح نتناول أهم المفاهيم والأسئلة المتعلقة بدرس الخلايا، مع توضيح المعلومات بطريقة مناسبة لطلاب الصف الرابع الابتدائي، ومراجعة أهم النقاط التي يحتاجها الطالب في الاختبارات.\n\n✅ شرح مبسط وواضح\n✅ مراجعة أهم مفاهيم الدرس\n✅ أمثلة وتوضيحات\n✅ أسئلة ومراجعة للدرس\n✅ مناسب للمذاكرة والاستعداد للاختبارات\n✅ متوافق مع منهج العلوم للصف الرابع الابتدائي\n\n🎓 تابع سلسلة علوم رابع ابتدائي على قناة الهداف التعليمية، واستعد للاختبارات بطريقة سهلة وممتعة.\n\n🌐 منصة الهداف التعليمية:\nhttps://alhadaf-edu.vercel.app\n أبطال الهداف على التيليجرام:\n https://t.me/alhadaaf_edu \nقناة الهداف على التيليجرام :\nhttps://t.me/alhadaf_edu\n\n📌 اشترك في القناة وفعل 🔔 الجرس ليصلك كل جديد من شروحات المنهج السعودي 1448هـ.\n#علوم_رابع_ابتدائي #الخلايا #شرح_الخلايا #علوم_رابع #رابع_ابتدائي #الدرس_الأول #الفصل_الأول #منهج_السعودية #علوم_1448 #الهداف_التعليمية",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "الخلايا",
    "youtubeId": "hTb8Li2JvIc",
    "youtubeUrl": "https://www.youtube.com/watch?v=hTb8Li2JvIc",
    "thumbnailUrl": "https://i.ytimg.com/vi/hTb8Li2JvIc/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1400,
    "likesCount": 140,
    "createdAt": "2026-09-03T07:10:07Z"
  },
  {
    "id": "yt_A6tlkwSvUfo",
    "title": "حل المشكلات بطريقة علمية | علوم ثاني متوسط الفصل الأول 1448هـ | شرح الدرس الثاني كام",
    "description": "في هذا الفيديو نقدم لكم شرح درس حل المشكلات بطريقة علمية من مادة العلوم للصف الثاني المتوسط، الفصل الدراسي الأول 1448هـ، شرحًا مبسطًا وشاملًا للدرس الثاني من فصل طبيعة العلم.\n\n📚 محتوى الدرس:\n\nما المقصود بالطرائق العلمية؟\nخطوات حل المشكلات بطريقة علمية.\nتحديد المشكلة والملاحظة.\nوضع الفر��ية واختبارها.\nالتخطيط وتنفيذ التجربة.\nجمع البيانات وتحليلها.\nاستخلاص النتائج والتواصل بها.\nالمتغير المستقل والمتغير التابع.\nالعوامل الثابتة والضابطة.\nأمثلة وتطبيقات على حل المشكلات بطريقة علمية.\nمراجعة أهم أسئلة الدرس.\n\n🎯 الفيديو مناسب لكل طالب وطالبة في ثاني متوسط يرغب في فهم درس حل المشكلات بطريقة علمية والاستعداد للاختبارات بطريقة سهلة ومبسطة.\n\n🌐 منصة الهداف التعليمية:\nhttps://alhadaf-edu.vercel.app/\n\n👍 لا تنسَ الاشتراك في القناة وتفعيل 🔔 الجرس ليصلك كل جديد من شروحات ومراجعات المنهج السعودي.\n\n🏷️ هاشتاجات\n\n#حل_المشكلات_بطريقة_علمية\n#علوم_ثاني_متوسط\n#ثاني_متوسط\n#علوم_ثاني_متوسط_ف1\n#الفصل_الأول_1448\n#منهج_السعودية\n#الهداف_التعليمية\n#شرح_علوم\n#الطرائق_العلمية\n#حل_المشكلات",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "science-mid",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "حل المشكلات بطريقة علمية",
    "youtubeId": "A6tlkwSvUfo",
    "youtubeUrl": "https://www.youtube.com/watch?v=A6tlkwSvUfo",
    "thumbnailUrl": "https://i.ytimg.com/vi/A6tlkwSvUfo/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1380,
    "likesCount": 138,
    "createdAt": "2026-09-02T08:37:04Z"
  },
  {
    "id": "yt_obBVyd9o-PM",
    "title": "شرح درس وسائل النقل | لغتي ثاني متوسط | الفصل الدراسي الأول 1448هـ | المنهج السعودي",
    "description": "شرح درس وسائل النقل من مادة لغتي للصف الثاني المتوسط ضمن منهج التعليم السعودي، الفصل الدراسي الأول 1448هـ / 2026م.\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا للدرس، مع توضيح أهم الأفكار والمفاهيم الواردة في الدرس، بطريقة تساعد الطالب على الفهم والمراجعة والاستعداد للاختبارات.\n\n📚 المادة: لغتي\n🎓 الصف: الثاني المتوسط\n📖 الدرس: وسائل النقل\n🇸🇦 المنهج: السعودي\n📅 الفصل الدراسي: الأول\n🗓️ العام الدراسي: 1448هـ / 2026م\n\nاشترك في قناة الهَدَّاف 🔔 لمتابعة شرح جميع دروس المنهج السعودي بطريقة سهلة ومبسطة.\n\n🌐 منصة الهَدَّاف:\nalhadaf-edu.vercel.app\n\nالهَدَّاف | لنشر العلم... وبناء مستقبل أفضل 🎓\n#وسائل_النقل #لغتي #ثاني_متوسط #لغتي_ثاني_متوسط #المنهج_السعودي #1448ه�� #الفصل_الأول #تعليم #الهَدَّاف",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "arabic-mid",
    "subjectName": "لغتي الخالدة",
    "term": 1,
    "unitTitle": "شرح درس وسائل النقل",
    "youtubeId": "obBVyd9o-PM",
    "youtubeUrl": "https://www.youtube.com/watch?v=obBVyd9o-PM",
    "thumbnailUrl": "https://i.ytimg.com/vi/obBVyd9o-PM/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1360,
    "likesCount": 136,
    "createdAt": "2026-09-02T07:54:33Z"
  },
  {
    "id": "yt_VpbB9nxSodE",
    "title": "أتعرّف على مكوّنات الصورة وأسمّيها | لغتي أول ابتدائي | الدرس الأول 1448هـ",
    "description": "شرح درس «أتعرّف على مكوّنات الصورة وأسمّيها» من مادة لغتي للصف الأول الابتدائي، ضمن الفصل الدراسي الأول للمنهج السعودي 1448هـ / 2026م.\n\nفي هذا الدرس يتعلم الطالب كيفية التعرّف على مكوّنات الصورة وتسميتها ووصف ما يراه فيها بطريقة سهلة ومبسطة، مع أنشطة وتدريبات تساعد على تنمية مهارات اللغة والملاحظة والتعبير.\n\n📚 المادة: لغتي\n🎓 الصف: الأول الابتدائي\n📖 الدرس: الأول\n🇸🇦 المنهج: السعودي\n📅 الفصل الدراسي: الأول\n🗓️ العام: 1448هـ / 2026م\n\nاشترك في قناة الهَدَّاف 🔔 لمتابعة شرح دروس المنهج السعودي بطريقة سهلة ومبسطة.\n🌐 منصة الهَدَّاف:\nalhadaf-edu.vercel.app\n#لغتي #أول_ابتدائي #لغتي_أول_ابتدائي #مكونات_الصورة #الدرس_الأول #المنهج_السعودي #1448هـ #تعليم #الهَدَّاف #الصف_الأول_الابتدائي#لغتي #أول_ابتدائي #المنهج_السعودي #الدرس_الأول #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 1,
    "subjectId": "arabic-elem",
    "subjectName": "لغتي الجميلة",
    "term": 1,
    "unitTitle": "أتعرّف على مكوّنات الصورة وأسمّيها",
    "youtubeId": "VpbB9nxSodE",
    "youtubeUrl": "https://www.youtube.com/watch?v=VpbB9nxSodE",
    "thumbnailUrl": "https://i.ytimg.com/vi/VpbB9nxSodE/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1340,
    "likesCount": 134,
    "createdAt": "2026-09-02T07:19:18Z"
  },
  {
    "id": "yt_w2myiV17Tw8",
    "title": "موقع الهَدَّاف التعليمي بدأ! 🎓 نحتاج معلمين من كل الدول العربية",
    "description": "🚀 انطلاق موقع الهَدَّاف التعليمي!\n\nنحن في الهَدَّاف نؤمن أن العلم يستحق أن يصل إلى كل طالب، وأن لكل معلم علمًا وخبرة يمكن أن تصنع فرقًا في حياة الطلاب.\n\n📚 لذلك نعلن عن بدء موقع الهَدَّاف التعليمي، وندعو المعلمين المتميزين من جميع الدول العربية للانضمام إلينا، وتقديم شروحاتهم ودروسهم التعليمية عبر القناة والمو��ع، والمساهمة في نشر العلم وبناء جيل أفضل.\n\n🎓 إذا كنت معلمًا في أي دولة عربية وتريد أن تشارك علمك وتفيد الطلاب، فنحن نرحب بك معنا.\n\n🌐 رابط منصة الهَدَّاف التعليمية:\nalhadaf-edu.vercel.app\n\n📱 للتواصل عبر واتساب:\n+966 567 662 653\n\n❤️ شارك الفيديو مع أي معلم قد يكون مهتمًا بالانضمام إلينا.\n\nالهَدَّاف | لنشر العلم... وبناء مستقبل أفضل 🎓\n#الهداف #منصة_الهداف #التعليم #معلمين #معلمون #تعليم #منصة_تعليمية #الوطن_العربي #دروس_تعليمية #shorts",
    "country": "sa",
    "stage": "secondary",
    "gradeNumber": 1,
    "subjectId": "arabic-sec",
    "subjectName": "الكفايات اللغوية",
    "term": 1,
    "unitTitle": "موقع الهَدَّاف التعليمي بدأ! 🎓 نحتاج معلمين من كل الدول العربية",
    "youtubeId": "w2myiV17Tw8",
    "youtubeUrl": "https://www.youtube.com/watch?v=w2myiV17Tw8",
    "thumbnailUrl": "https://i.ytimg.com/vi/w2myiV17Tw8/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1320,
    "likesCount": 132,
    "createdAt": "2026-09-02T06:39:38Z"
  },
  {
    "id": "yt_ZSMUvMTZ7OE",
    "title": "العلم وعملياته –المهارات العلمية | أولى متوسط | المهارات العلمية  | علوم 1448 هـ",
    "description": "شرح درس \"العلم وعملياته\" من كتاب العلوم للصف الأول المتوسط | الفصل الدراسي الأول | المنهج السعودي 1448 هـ / 2026\n\n📌 في هذا الفيديو:\n• تعريف العلم وخطوات المنهج العلمي\n• شرح عمليات العلم: الملاحظة – الاستقصاء – التجربة – التحليل – الاستنتاج\n• الفرق بين النظرية والقانون العلمي\n• ملخص الدرس للمذاكرة السريعة\n• حل أسئلة الدرس والتدريبات\n\n👨‍🏫 الفيديو مناسب لطلاب وطالبات الصف الأول المتوسط في المنهج السعودي الجديد\n\n✅ لا تنسَ الاشتراك في قناة الهداف وتفعيل الجرس 🔔 ليصلك كل جديد\n\n🏷️ #العلم_وعملياته #علوم_أولى_متوسط #الفصل_الأول #المنهج_السعودي #قناة_الهداف\n\n━━━━━━━━━━━━━━━━━━━━\n📚 كلمات دلالية: شرح العلم وعملياته، علوم أولى متوسط، المنهج السعودي الجديد، خطوات المنهج العلمي، الفصل الأول علوم أولى متوسط، ملخص علوم أولى متوسط، حل درس العلم وعملياته، تلخيص علوم 1 متوسط، الملاحظة والاستقصاء والتج��بة، شرح منهج علوم أولى متوسط 1448، دروس علوم أولى متوسط، قناة الهداف، تعليم سعودي، وزارة التعليم السعودية",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 1,
    "subjectId": "science-mid",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "العلم وعملياته –المهارات العلمية",
    "youtubeId": "ZSMUvMTZ7OE",
    "youtubeUrl": "https://www.youtube.com/watch?v=ZSMUvMTZ7OE",
    "thumbnailUrl": "https://i.ytimg.com/vi/ZSMUvMTZ7OE/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1300,
    "likesCount": 130,
    "createdAt": "2026-08-30T09:22:40Z"
  },
  {
    "id": "yt_JVVLXNlAPlk",
    "title": "النباتات وأجزاؤها 🔬 شرح مبسط للأطفال | علوم أولى ابتدائي | المنهج السعودي 1448",
    "description": "شرح درس \"النباتات وأجزاؤها\" من كتاب العلوم للصف الأول الابتدائي | الفصل الدراسي الأول | المنهج السعودي 1448 هـ / 2026\n\n📌 في هذا الفيديو:\n• شرح مبسط وممتع للأطفال عن النباتات وأجزائها\n• تعريف الجذر والساق والورقة والزهرة والثمرة\n• رسم توضيحي واضح لأجزاء النبات\n• ملخص سريع للمذاكرة قبل الاختبار\n• حل أسئلة الدرس والتدريبات\n\n👶 الفيديو مخصص لطلاب وطالبات الصف الأول الابتدائي في المنهج السعودي الجديد\n\n✅ لا تنسَ الاشتراك في قناة الهداف وتفعيل الجرس 🔔 ليصل�� كل جديد\n\n🏷️ #النباتات_وأجزاؤها #علوم_أولى_ابتدائي #الفصل_الأول #قناة_الهداف\n\n━━━━━━━━━━━━━━━━━━━━\n📚 كلمات دلالية: شرح النباتات وأجزاؤها، علوم أولى ابتدائي، المنهج السعودي الجديد، أجزاء النبات للأطفال، الفصل الأول علوم أولى ابتدائي، ملخص علوم أولى ابتدائي، حل درس النباتات وأجزاؤها، تلخيص علوم 1 ابتدائي، شرح منهج علوم أولى ابتدائي 1448، دروس علوم أولى ابتدائي، قناة الهداف، تعليم سعودي، وزارة التعليم السعودية",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 1,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "النباتات وأجزاؤها 🔬 شرح مبسط للأطفال",
    "youtubeId": "JVVLXNlAPlk",
    "youtubeUrl": "https://www.youtube.com/watch?v=JVVLXNlAPlk",
    "thumbnailUrl": "https://i.ytimg.com/vi/JVVLXNlAPlk/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1280,
    "likesCount": 128,
    "createdAt": "2026-08-30T09:11:16Z"
  },
  {
    "id": "yt_IGevlgviiLE",
    "title": "حل وشرح درس قبس من القرآن | لغتي الصف الأول المتوسط | ترم اول",
    "description": "شرح درس \"قبس من القرآن\" من كتاب لغتي للصف الأول المتوسط | المنهج السعودي 1448 هـ / 2026\n\n📌 في هذا الفيديو:\n• شرح مبسط لدرس قبس من القرآن\n• أهم المعاني والمفر��ات\n• ملخص الدرس للمذاكرة السريعة\n• حل الأسئلة والتدريبات\n\n👨‍🏫 الفيديو مناسب لطلاب وطالبات الصف الأول المتوسط في المنهج السعودي\n\n✅ لا تنسَ الاشتراك في قناة الهداف وتفعيل الجرس 🔔 ليصلك كل جديد\n\n🏷️ #قبس_من_القرآن #لغتي #أولى_متوسط #المنهج_السعودي #قناة_الهداف\n\n🔗 تابعنا على يوتيوب: قناة الهداف\n\n━━━━━━━━━━━━━━━━━━━━\n📚 كلمات دلالية: شرح قبس من القرآن، لغتي أولى متوسط، المنهج السعودي الجديد، ملخص لغتي أول متوسط، حل درس قبس من القرآن، تلخيص لغتي 1 متوسط، شرح منهج لغتي أولى متوسط 1447، دروس لغتي أولى متوسط، قناة الهداف، تعليم سعودي",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 1,
    "subjectId": "arabic-mid",
    "subjectName": "لغتي الخالدة",
    "term": 1,
    "unitTitle": "حل وشرح درس قبس من القرآن",
    "youtubeId": "IGevlgviiLE",
    "youtubeUrl": "https://www.youtube.com/watch?v=IGevlgviiLE",
    "thumbnailUrl": "https://i.ytimg.com/vi/IGevlgviiLE/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1260,
    "likesCount": 126,
    "createdAt": "2026-08-30T08:32:25Z"
  },
  {
    "id": "yt_hHAHtNUyHPM",
    "title": "الدولة الأموية وأبرز خلفائها | الدراسات الاجتماعية ثاني متوسط | الفصل الأول 1448ه",
    "description": "شرح مبسط ��درس الدولة الأموية وأبرز خلفائها (41–132هـ) في مادة الدراسات الاجتماعية للصف الثاني المتوسط، الفصل الدراسي الأول 1448هـ، وفق منهج المملكة العربية السعودية.\n\nفي هذا الدرس نتعرف على:\n📌 نشأة الدولة الأموية وقيامها.\n📌 سبب تسمية الدولة الأموية.\n📌 معاوية بن أبي سفيان وأهم أعماله.\n📌 أبرز خلفاء الدولة الأموية وإنجازاتهم.\n📌 عبدالملك بن مروان وأهم أعماله.\n📌 مروان بن محمد وآخر خلفاء الدولة الأموية.\n📌 أهم إنجازات الدولة الأموية وأثرها في التاريخ الإسلامي.\n\n🎯 شرح سهل ومناسب للطلاب، مع التركيز على أهم النقاط التي تساعد على فهم الدرس والمراجعة والاستعداد للاختبارات.\n\n📚 المادة: الدراسات الاجتماعية\n🎓 الصف: الثاني المتوسط\n📖 الفصل الدراسي: الأول\n📅 العام الدراسي: 1448هـ\n🏛️ الدرس: الدولة الأموية وأبرز خلفائها (41–132هـ)\n\nإذا استفدت من الشرح، لا تنسَ الاشتراك في القناة 👍 وتفعيل 🔔 التنبيهات ليصلك كل جديد.\n\n#الدولة_الأموية #ثاني_متوسط #الدراسات_الاجتماعية #اجتماعيات #منهج_السعودية",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "social-mid",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "الدولة الأموية وأبرز خلفائها",
    "youtubeId": "hHAHtNUyHPM",
    "youtubeUrl": "https://www.youtube.com/watch?v=hHAHtNUyHPM",
    "thumbnailUrl": "https://i.ytimg.com/vi/hHAHtNUyHPM/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1240,
    "likesCount": 124,
    "createdAt": "2026-08-26T22:17:01Z"
  },
  {
    "id": "yt_LewEczZm3d0",
    "title": "شكل الأرض | الدراسات الاجتماعية أول متوسط | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "في هذا الفيديو نقدم شرحًا مبسطًا وممتعًا لدرس **شكل الأرض** في مادة الدراسات الاجتماعية للصف الأول المتوسط، الفصل الدراسي الأول 1448هـ.\n\n🌍 سنتعرف في الدرس على شكل الأرض، والأدلة التي توضح كرويتها، مع الاستعانة بالأمثلة والصور والخرائط لتسهيل فهم الدرس وتثبيت المعلومات.\n\n📚 **محتويات الدرس:**\n\n* شكل الأرض.\n* كروية الأرض.\n* الأدلة على كروية الأرض.\n* أهم المفاهيم والمعلومات الواردة في الدرس.\n* أمثلة وصور توضيحية تساعد على فهم الدرس.\n\n🎯 الشرح مناسب لطلاب وطالبات **الصف الأول المتوسط** وفق منهج الدراسات الاجتماعية في المملكة العربية السعودية.\n\n📌 **المادة:** الدراسات الاجتماعية\n📌 **الصف:** الأول المتوسط\n📌 **الفصل الدراسي:** الأول\n📌 **العام الدراسي:** 1448هـ\n📌 **الدرس:** الثاني – شكل الأرض\n\nإذا استفدت من الشرح، لا تنسَ 👍 الإعجاب بالفيديو والاشتراك في القناة 🔔 وتفعيل التنبيهات ليصلك كل جديد.\n\n#شكل_الأرض #دراسات_اجتماعية #أول_متوسط #الفصل_الأول #1448هـ",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 1,
    "subjectId": "social-mid",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "شكل الأرض",
    "youtubeId": "LewEczZm3d0",
    "youtubeUrl": "https://www.youtube.com/watch?v=LewEczZm3d0",
    "thumbnailUrl": "https://i.ytimg.com/vi/LewEczZm3d0/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1220,
    "likesCount": 122,
    "createdAt": "2026-08-26T22:08:57Z"
  },
  {
    "id": "yt_1NMuD5zFscc",
    "title": "الهوية الوطنية | الدراسات الاجتماعية رابع ابتدائي | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "شرح مبسط ومميز لدرس الهوية الوطنية في مادة الدراسات الاجتماعية للصف الرابع الابتدائي، الفصل الدراسي الأول 1448هـ.\n\nفي هذا الدرس نتعرف على مفهوم الهوية الوطنية وأهميتها، وكيف تعبر عن الانتماء للوطن والاعتزاز به، مع التعرف على القيم والمبادئ التي تعزز الهوية الوطنية لدى أبناء الوطن.\n\n📚 محتويات الدرس:\n🇸🇦 مفهوم الهوية الوطنية\n💚 أهمية الهوية الوطنية\n🤝 الانتماء والاعتزاز بالوطن\n🛡️ القيم والمبادئ الوطنية\n🌟 دور المواطن في المحافظة على هوية وطنه\n📝 أمثلة وتطبيقات تساعد على فهم الدرس\n\n📌 المادة: الدراسات الاجتماعية\n📌 الصف: الرابع الابتدائي\n📌 الوحدة: المواطنة\n📌 الدرس: الثاني – الهوية الوطنية\n📌 الفصل الدراسي: الأول\n📌 العام الدراسي: 1448هـ\n\nإذا استفدت من الشرح، لا تنسَ الاشتراك في القناة 👍 وتفعيل 🔔 التنبيهات ليصلك كل جديد.\n\n#الهوية_الوطنية #رابع_ابتدائي #الدراسات_الاجتماعية #اجتماعيات #1448هـ",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "social-elem",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "الهوية الوطنية",
    "youtubeId": "1NMuD5zFscc",
    "youtubeUrl": "https://www.youtube.com/watch?v=1NMuD5zFscc",
    "thumbnailUrl": "https://i.ytimg.com/vi/1NMuD5zFscc/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1200,
    "likesCount": 120,
    "createdAt": "2026-08-26T22:04:01Z"
  },
  {
    "id": "yt_GqkYZwyn858",
    "title": "المصطلحات التاريخية | الدراسات الاجتماعية سادس ابتدائي | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "شرح مبسط ومتكامل لدرس المصطلحات التاريخية في مادة الدراسات الاجتماعية للصف السادس الابتدائي، الفصل الدراسي الأول 1448هـ.\n\nفي هذا الدرس نتعرف على أهم المصطلحات التاريخية، وكيف نستخدمها لفهم الأحداث التاريخية وترتيبها ووصفها بطريقة صحيحة، مع أمثلة وتطبيقات تساعد الطالب على استيعاب الدرس بسهولة.\n\n📚 محاور الدرس:\n\nالتعرف على أهم المصطلحات التاريخية.\nفهم معاني المصطلحات واستخدامها.\nالتمييز بين العصور والعقود والقرون.\nالتعرف على مفاهيم الزمن التاريخي.\nتطبيق المصطلحات على الأحداث التاريخية.\nمراجعة أهم أفكار الدرس بطريقة سهلة.\n\n📌 المادة: الدراسات الاجتماعية\n📌 الصف: السادس الابتدائي\n📌 الوحدة: التاريخ\n📌 الدرس: الثاني – المصطلحات التاريخية\n📌 الفصل الدراسي: الأول\n📌 العام الدراسي: 1448هـ\n\n🎯 الشرح مناسب للطلاب والطالبات للمذاكرة والمراجعة والاستعداد للاختبارات.\n\n👍 إذا استفدت من الفيديو، لا تنسَ الاشتراك في القناة وتفعيل 🔔 التنبيهات ليصلك شرح باقي دروس المنهج.\n\n#المصطلحات_التاريخية #دراسات_اجتماعية #سادس_ابتدائي #منهج_السعودية #1448هـ",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 6,
    "subjectId": "social-elem",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "المصطلحات التاريخية",
    "youtubeId": "GqkYZwyn858",
    "youtubeUrl": "https://www.youtube.com/watch?v=GqkYZwyn858",
    "thumbnailUrl": "https://i.ytimg.com/vi/GqkYZwyn858/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1180,
    "likesCount": 118,
    "createdAt": "2026-08-26T21:58:50Z"
  },
  {
    "id": "yt_ouPS7iHOioo",
    "title": "مفهوم التاريخ | الدراسات الاجتماعية سادس ابتدائي | الفصل الأول 1448هـ | الدرس الأول",
    "description": "شرح درس مفهوم التاريخ في مادة الدراسات الاجتماعية للصف السادس الابتدائي، الفصل الدراسي الأول 1448هـ، الدرس ��لأول من الوحدة الأولى «التاريخ».\n\nفي هذا الدرس نتعرف على:\n📚 ما المقصود بالتاريخ؟\n⏳ علاقة التاريخ بالماضي والزمن.\n🏛️ أهمية دراسة التاريخ.\n🌍 فوائد التاريخ في حفظ تراث الأمم والمجتمعات.\n🇸🇦 دور التاريخ في تعزيز الهوية والمواطنة.\n💡 كيف يساعدنا التاريخ على فهم الحاضر وتوقع المستقبل؟\n📝 أمثلة وأنشطة تساعد الطالب على فهم الدرس واستيعابه.\n\nالدرس مناسب لطلاب وطالبات الصف السادس الابتدائي – الدراسات الاجتماعية – الفصل الدراسي الأول 1448هـ.\n\n📌 المادة: الدراسات الاجتماعية\n📌 الصف: السادس الابتدائي\n📌 الوحدة: التاريخ\n📌 الدرس: الأول – مفهوم التاريخ\n📌 الفصل الدراسي: الأول\n📌 العام الدراسي: 1448هـ\n\nلا تنسَ الاشتراك في القناة 👍 وتفعيل 🔔 التنبيهات ليصلك شرح الدروس الجديدة.",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 6,
    "subjectId": "social-elem",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "مفهوم التاريخ",
    "youtubeId": "ouPS7iHOioo",
    "youtubeUrl": "https://www.youtube.com/watch?v=ouPS7iHOioo",
    "thumbnailUrl": "https://i.ytimg.com/vi/ouPS7iHOioo/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1160,
    "likesCount": 116,
    "createdAt": "2026-08-26T21:53:52Z"
  },
  {
    "id": "yt_muSwE2f2IyE",
    "title": "مقارنة الأعداد النسبية وترتيبها | رياضيات الصف الثاني المتوسط | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "في هذا الدرس من مادة الرياضيات للصف الثاني المتوسط، نتعلم مقارنة الأعداد النسبية وترتيبها بطريقة سهلة وواضحة، مع توضيح كيفية استخدام خط الأعداد والرموز المناسبة للمقارنة بين الأعداد النسبية.\n\n📚 محتويات الدرس:\n\nمقارنة الأعداد النسبية.\nترتيب الأعداد النسبية تصاعديًا وتنازليًا.\nاستخدام خط الأعداد في المقارنة والترتيب.\nتطبيقات وأمثلة متنوعة.\nتبسيط المفاهيم بطريقة مناسبة لطلاب الصف الثاني المتوسط.\n\n🎯 تابع الدرس حتى النهاية، وطبّق الأمثلة لتتقن مهارة مقارنة وترتيب الأعداد النسبية.\n\n📌 المادة: الرياضيات\n📌 الصف: الثاني المتوسط\n📌 الفصل: الأول\n📌 العام الدراسي: 1448هـ\n📌 الدرس: الثاني\n\nإذا أعجبك الشرح، لا تنسَ الاشتراك في القناة وتفعيل 🔔 التنبيهات ليصلك كل جديد.",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "math-mid",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "مقارنة الأعداد النسبية وترتيبها",
    "youtubeId": "muSwE2f2IyE",
    "youtubeUrl": "https://www.youtube.com/watch?v=muSwE2f2IyE",
    "thumbnailUrl": "https://i.ytimg.com/vi/muSwE2f2IyE/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1140,
    "likesCount": 114,
    "createdAt": "2026-08-26T21:43:02Z"
  },
  {
    "id": "yt_3_F4JdAFR9o",
    "title": "التصنيف وفق اكثر من خاصية | رياضيات الصف الأول الابتدائى | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "في هذا الفيديو نقدم شرحًا مبسطًا لدرس التصنيف وفق أكثر من خاصية في مادة الرياضيات للصف الأول الابتدائي، ضمن الفصل الدراسي الأول 1448هـ من المنهج السعودي.\n\n📚 يتناول الدرس:\n\nتصنيف الأشياء و��ق أكثر من خاصية.\nملاحظة أوجه التشابه والاختلاف بين الأشكال والأشياء.\nالتصنيف حسب اللون والشكل والحجم وغيرها من الخصائص.\nتطبيقات وأمثلة مبسطة تساعد الطالب على فهم الدرس.\nتدريبات على مهارة التصنيف بطريقة سهلة وممتعة.\n\n🎯 الدرس: التصنيف وفق أكثر من خاصية\n📖 المادة: رياضيات\n👦 الصف: الأول الابتدائي\n📚 الفصل الأول: المقارنة والتصنيف\n📅 العام الدراسي: 1448هـ\n\nإذا أعجبك الشرح لا تنسَ 👍 الإعجاب بالفيديو والاشتراك في القناة 🔔 ليصلك المزيد من شروحات الرياضيات للمنهج السعودي.\n#رياضيات_اول_ابتدائي #التصنيف_وفق_أكثر_من_خاصية #المنهج_السعودي #رياضيات_1448 #اول_ابتدائي #الفصل_الأول #المقارنة_والتصنيف #تعليم",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 1,
    "subjectId": "math-elem",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "التصنيف وفق اكثر من خاصية",
    "youtubeId": "3_F4JdAFR9o",
    "youtubeUrl": "https://www.youtube.com/watch?v=3_F4JdAFR9o",
    "thumbnailUrl": "https://i.ytimg.com/vi/3_F4JdAFR9o/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1120,
    "likesCount": 112,
    "createdAt": "2026-08-26T21:16:19Z"
  },
  {
    "id": "yt_Zbm42P9eyAY",
    "title": "القوى والأسس | رياضيات الصف الأول المتوسط | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "🎯 الدرس الثاني | رياضيات أول متوسط | الفصل الدراسي الأول 1448هـ\nفي هذا الدرس نتعرف على علامات القوى والأسس بطريقة سهلة ومبسطة، ضمن منهج رياضيات الصف الأول المتوسط – الفصل الدراسي الأول 1448هـ.\n\n📚 سنتعلم في الفيديو:\n\nمفهوم القوة والأساس والأس.\nكيفية قراءة القوى وكتابتها.\nفهم معنى الأسس بطريقة مبسطة.\nتطبيقات وأمثلة متنوعة على القوى والأسس.\nحل تدريبات تساعدك على إتقان الدرس.\n\nإذا استفدت من الشرح 👍 لا تنسَ الإعجاب بالفيديو والاشتراك في القناة وتفعيل الجرس 🔔 ليصلك كل جديد.\n #رياضيات #اول_متوسط #القوى_والأسس #رياضيات_1448 #المنهج_السعودي #الفصل_الأول #تعليم #الصف_الأول_المتوسط_",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 1,
    "subjectId": "math-mid",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "القوى والأسس",
    "youtubeId": "Zbm42P9eyAY",
    "youtubeUrl": "https://www.youtube.com/watch?v=Zbm42P9eyAY",
    "thumbnailUrl": "https://i.ytimg.com/vi/Zbm42P9eyAY/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1100,
    "likesCount": 110,
    "createdAt": "2026-08-26T21:01:15Z"
  },
  {
    "id": "yt_JAY8nTvfM3Y",
    "title": "القيمة المنزلية ضمن الملايين | رياضيات رابع ابتدائي | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "شرح القيمة المنزلية ضمن الملايين | رياضيات رابع ابتدائي | الفصل الأول 1448هـ | الدرس الثاني.\n\nفي هذا ال��يديو نقدم شرحًا مبسطًا لدرس **القيمة المنزلية ضمن الملايين** في مادة الرياضيات للصف الرابع الابتدائي، مع توضيح القيمة المنزلية للأرقام وقراءة وكتابة الأعداد ضمن الملايين بطريقة سهلة ومنظمة.\n\n📚 سنتعرف في الدرس على:\n\n* القيمة المنزلية للأرقام ضمن الملايين.\n* قراءة الأعداد وكتابتها.\n* تحديد قيمة الرقم بحسب منزلته.\n* فهم منازل الأعداد الكبيرة.\n* حل أمثلة وتطبيقات على الدرس.\n* أهم الأفكار التي يحتاجها الطالب للاستعداد للاختبارات.\n\n🎯 الفيديو مناسب لطلاب **الصف الرابع الابتدائي** وفق المنهج السعودي للفصل الدراسي الأول 1448هـ.\n\n📌 تابع قناة **الهَدَّاف** للمزيد من شروحات الرياضيات والمناهج السعودية.\n\n🔔 اشترك في القناة وفعل الجرس ليصلك كل جديد.\n\n#القيمة_المنزلية #رياضيات_رابع_ابتدائي #رابع_ابتدائي #رياضيات #1448هـ #المنهج_السعودي #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "math-elem",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "القيمة المنزلية ضمن الملايين",
    "youtubeId": "JAY8nTvfM3Y",
    "youtubeUrl": "https://www.youtube.com/watch?v=JAY8nTvfM3Y",
    "thumbnailUrl": "https://i.ytimg.com/vi/JAY8nTvfM3Y/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1080,
    "likesCount": 108,
    "createdAt": "2026-08-26T20:17:53Z"
  },
  {
    "id": "yt_3FcbGYFT9GY",
    "title": "العوامل الأولية | رياضيات سادس ابتدائي | الفصل الأول 1448هـ | الدرس الثاني",
    "description": "**شرح العوامل الأولية | الرياضيات | الصف السادس الابتدائي | الفصل الأول 1448هـ | الدرس الثاني**\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا لدرس **العوامل الأولية** في مادة **الرياضيات للصف السادس الابتدائي**، ضمن **الفصل الدراسي الأول 1448هـ**.\n\n📚 **في هذا الدرس سنتعرف على:**\n\n* مفهوم العوامل الأولية.\n* الفرق بين العدد الأولي والعدد غير الأولي.\n* كيفية تحليل الأعداد إلى عواملها الأولية.\n* استخدام طرق مختلفة لإيجاد العوامل الأولية.\n* حل أمثلة وتطبيقات على درس العوامل الأولية.\n* أهم الأفكار والأسئلة التي تساعدك على الاستعداد للاختبارات.\n\n🎯 شرح مناسب لطلاب **الصف السادس الابتدائي** في المنهج السعودي، بط��يقة سهلة ومنظمة تساعدك على فهم الدرس وتطبيقه وحل المسائل بنفسك.\n\n📌 تابع قناة **الهَدَّاف** للمزيد من شروحات الرياضيات والمناهج السعودية لجميع الصفوف الدراسية.\n\n🔔 اشترك في القناة وفعل الجرس ليصلك كل جديد.\n\n#العوامل_الأولية #رياضيات #سادس_ابتدائي #الصف_السادس #رياضيات_سادس #1448هـ #الفصل_الأول #المنهج_السعودي #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 6,
    "subjectId": "math-elem",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "العوامل الأولية",
    "youtubeId": "3FcbGYFT9GY",
    "youtubeUrl": "https://www.youtube.com/watch?v=3FcbGYFT9GY",
    "thumbnailUrl": "https://i.ytimg.com/vi/3FcbGYFT9GY/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1060,
    "likesCount": 106,
    "createdAt": "2026-08-26T19:44:17Z"
  },
  {
    "id": "yt_ynmTekWC13I",
    "title": "شرح  الدراسات الاجتماعية | الصف الرابع الابتدائى | الفصل الأول 1448هـ| الدرس الأول",
    "description": "شرح الدراسات الاجتماعية | الصف الرابع الابتدائي | الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وسهلًا لدرس الدراسات الاجتماعية للصف الرابع الابتدائي ضمن الفصل الدراسي الأول 1448هـ.\n\n📚 سنتناول أهم المفاهيم والأفكار الوارد�� في الدرس الأول بطريقة منظمة تساعد الطلاب على الفهم والاستيعاب، مع توضيح المعلومات المهمة التي يحتاجها الطالب للمذاكرة والاستعداد للاختبارات.\n\n🎯 الفيديو مناسب لطلاب الصف الرابع الابتدائي في المنهج السعودي، ويساعد على مراجعة الدرس وتثبيت المعلومات بطريقة سهلة ومبسطة.\n\n📌 تابع قناة الهَدَّاف لمشاهدة المزيد من شروحات المناهج السعودية لجميع الصفوف والمواد.\n\n🔔 اشترك في القناة وفعل الجرس ليصلك كل جديد من الدروس والشروحات التعليمية.\n\n#الدراسات_الاجتماعية #رابع_ابتدائي #الصف_الرابع_الابتدائي #1448هـ #الفصل_الأول #المنهج_السعودي #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "social-elem",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "شرح  الدراسات الاجتماعية",
    "youtubeId": "ynmTekWC13I",
    "youtubeUrl": "https://www.youtube.com/watch?v=ynmTekWC13I",
    "thumbnailUrl": "https://i.ytimg.com/vi/ynmTekWC13I/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1040,
    "likesCount": 104,
    "createdAt": "2026-08-25T11:12:55Z"
  },
  {
    "id": "yt_lKUy2pZ1vls",
    "title": "شرح المجموعة الشمسية | الدراسات الاجتماعية الصف الاول المتوسط الفصل الأول 1448هـ | الدرس الأول",
    "description": "شرح المجموعة الشمسية | الدراسات الاجتماعية | الصف الأول المتوسط | الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا لدرس المجموعة الشمسية في مادة الدراسات الاجتماعية للصف الأول المتوسط – الفصل الدراسي الأول 1448هـ.\n\n📚 سنتعرف في الدرس على:\n\n- مفهوم المجموعة الشمسية.\n- الشمس ومكانتها في المجموعة الشمسية.\n- الكواكب التي تتكون منها المجموعة الشمسية.\n- ترتيب الكواكب حول الشمس.\n- أهم خصائص الكواكب.\n- حركة الكواكب ودورانها حول الشمس.\n- معلومات مهمة تساعدك على فهم الدرس والاستعداد للاختبارات.\n\n🎯 شرح مناسب لطلاب الصف الأول المتوسط وفق المنهج السعودي، بطريقة سهلة ومنظمة تساعدك على فهم ��لدرس وتثبيت المعلومات.\n\n📌 تابع قناة الهَدَّاف لمزيد من الشروحات التعليمية لجميع المواد والمراحل الدراسية.\n\n👍 لا تنسَ الاشتراك في القناة وتفعيل 🔔 الجرس ليصلك كل جديد.\n\n#المجموعة_الشمسية #دراسات_اجتماعية #اولى_متوسط #الصف_الأول_المتوسط #الدراسات_الاجتماعية #1448هـ #الفصل_الأول #المنهج_السعودي #الهَدَّاف",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 1,
    "subjectId": "social-mid",
    "subjectName": "الدراسات الاجتماعية",
    "term": 1,
    "unitTitle": "شرح المجموعة الشمسية",
    "youtubeId": "lKUy2pZ1vls",
    "youtubeUrl": "https://www.youtube.com/watch?v=lKUy2pZ1vls",
    "thumbnailUrl": "https://i.ytimg.com/vi/lKUy2pZ1vls/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1020,
    "likesCount": 102,
    "createdAt": "2026-08-25T11:08:28Z"
  },
  {
    "id": "yt_kugCtC47aZo",
    "title": "شرح حركة الكواكب والجاذبية | فزياء الصف الثانى الثانوى  الفصل الأول 1448هـ | الدرس الأول",
    "description": "شرح حركة الكواكب والجاذبية | فيزياء الصف الثاني الثانوي | الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا لدرس حركة الكواكب والجاذبية في مادة الفيزياء للصف الثاني الثانوي – الفصل الدراسي الأول 1448هـ.\n\n📚 سنتعرف في الدرس على:\n\n- مفهوم الجاذبية وقوة الجذب بين الأجسام.\n- كيفية حركة الكواكب حول الشمس.\n- العلاقة بين الجاذبية وحركة الأجرام السماوية.\n- القوانين والمفاهيم الأساسية المرتبطة بحركة الكواكب.\n- أهم الأفكار والنقاط التي تساعدك على فهم الدرس وحل الأسئلة.\n- أمثلة وتطبيقات تساعد على تثبيت المعلومات.\n\n🎯 الفيديو مناسب لطلاب الصف الثاني الثانوي في المنهج السعودي، ويساعدك على فهم الدرس بطريقة سهلة ومنظمة والاستعداد للاختبارات.\n\n📌 لا تنسَ الاشتراك في قناة الهَدَّاف وتفعيل 🔔 الجرس ليصلك كل جديد من شروحات ودروس المنهج السعودي.\n\n#فيزياء #ثاني_ثانوي #حركة_الكواكب #الجاذبية #المنهج_السعودي #الفصل_الأول #1448هـ #الهَدَّاف",
    "country": "sa",
    "stage": "secondary",
    "gradeNumber": 2,
    "subjectId": "physics-sec",
    "subjectName": "الفيزياء",
    "term": 1,
    "unitTitle": "شرح حركة الكواكب والجاذبية",
    "youtubeId": "kugCtC47aZo",
    "youtubeUrl": "https://www.youtube.com/watch?v=kugCtC47aZo",
    "thumbnailUrl": "https://i.ytimg.com/vi/kugCtC47aZo/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 1000,
    "likesCount": 100,
    "createdAt": "2026-08-25T10:59:47Z"
  },
  {
    "id": "yt_nSko5mgJXTc",
    "title": "شرح الاعداد النسبية | رياضيات الصف الثانى المتوسط الفص�� الأول 1448هـ | الدرس الأول",
    "description": "شرح الأعداد النسبية | رياضيات الصف الثاني المتوسط الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا لدرس الأعداد النسبية في مادة الرياضيات للصف الثاني المتوسط، الفصل الدراسي الأول 1448هـ.\n\n📚 سنتعرف خلال الدرس على مفهوم الأعداد النسبية، وكيفية تمثيلها وقراءتها، مع توضيح أهم الأفكار والأمثلة بطريقة سهلة تساعد الطلاب على الفهم والمراجعة والاستعداد للاختبارات.\n\n🎯 محتويات الدرس:\n\n- مفهوم الأعداد النسبية.\n- التعرف على صور الأعداد النسبية.\n- تمثيل الأعداد النسبية.\n- مقارنة الأعداد النسبية.\n- أمثلة وتدريبات متنوعة.\n- أهم النقاط التي يحتاج الطالب إلى مراجعتها.\n\n👨‍🏫 الشرح مناسب لطلاب الصف الثاني المتوسط ويساعد على تأسيس المفاهيم الرياضية بطريقة مبسطة ومنظمة.\n\n👍 إذا استفدت من الفيديو، لا تنسَ ��لاشتراك في قناة الهَدَّاف وتفعيل 🔔 التنبيهات ليصلك كل جديد من شروحات المناهج التعليمية.\n\n#الرياضيات #الأعداد_النسبية #ثاني_متوسط #الهَدَّاف #الفصل_الأول #1448هـ",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "math-mid",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "شرح الاعداد النسبية",
    "youtubeId": "nSko5mgJXTc",
    "youtubeUrl": "https://www.youtube.com/watch?v=nSko5mgJXTc",
    "thumbnailUrl": "https://i.ytimg.com/vi/nSko5mgJXTc/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 980,
    "likesCount": 98,
    "createdAt": "2026-08-25T09:48:37Z"
  },
  {
    "id": "yt_Oinlpk_k1BU",
    "title": "شرح خصائص شوكيات الجلد | احياء الصف الثانى الثانوى الفصل الأول 1448هـ | الدرس الأول",
    "description": "شرح خصائص شوكيات الجلد | أحياء الصف الثاني الثانوي الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الدرس نقدم شرحًا مبسطًا وشاملًا لدرس خصائص شوكيات الجلد ضمن مادة الأحياء للصف الثاني الثانوي، الفصل الدراسي الأول 1448هـ.\n\nسنتعرف على أهم خصائص شوكيات الجلد، وتركيب أجسامها، والصفات التي تميزها عن غيرها من الحيوانات، مع توضيح المفاهيم المهمة بطريقة سهلة تساعد الطلاب على الفهم والمراجعة والاستعداد للاختبارات.\n\n📚 محتوى الدرس:\n• خصائص شوكيات الجلد.\n• تركيب جسم شوكيات الجلد.\n• التناظر في شوكيات الجلد.\n• الجهاز الوعائي المائي ووظائفه.\n• الحركة والتغذية والتنفس والإخراج.\n• أمثلة على شوكيات الجلد.\n• أهم النقاط والأسئلة المهمة على الدرس.\n\n🎯 شرح مناسب لطلاب الصف الثاني الثانوي – أحياء – الفصل الدراسي الأول 1448هـ.\n\nلا تنسَ الاشتراك في قناة الهَدَّاف وتفعيل 🔔 التنبيهات ليصلك كل جديد من شروحات المناهج التعليمية.\n\n#أحياء #ثاني_ثانوي #شوكيات_الجلد #خصائص_شوكيات_الجلد #الفصل_الأول #1448هـ #الهَدَّاف",
    "country": "sa",
    "stage": "secondary",
    "gradeNumber": 2,
    "subjectId": "bio-sec",
    "subjectName": "الأحياء",
    "term": 1,
    "unitTitle": "شرح خصائص شوكيات الجلد",
    "youtubeId": "Oinlpk_k1BU",
    "youtubeUrl": "https://www.youtube.com/watch?v=Oinlpk_k1BU",
    "thumbnailUrl": "https://i.ytimg.com/vi/Oinlpk_k1BU/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 960,
    "likesCount": 96,
    "createdAt": "2026-08-25T09:34:13Z"
  },
  {
    "id": "yt_zJVro_SvfDE",
    "title": "شرح القيمة المنزلية ضمن مئات الألوف | الرياضيات الصف الرابع ابتدائى الفصل الأول 1448هـ | الدرس الأول",
    "description": "📚 شرح القيمة المنزلية ضمن مئات الألوف | الرياضي��ت الصف الرابع ابتدائي | الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا لدرس القيمة المنزلية ضمن مئات الألوف في مادة الرياضيات للصف الرابع الابتدائي، الفصل الدراسي الأول 1448هـ.\n\n🎯 في هذا الدرس سنتعلم:\n\n- التعرف على القيمة المنزلية للأرقام.\n- قراءة الأعداد وكتابتها ضمن مئات الألوف.\n- تحديد منزلة الرقم في العدد.\n- معرفة القيمة المنزلية للرقم حسب موقعه.\n- التمييز بين المنزلة والقيمة المنزلية.\n- حل أمثلة وتدريبات متنوعة على الدرس.\n\n👨‍🏫 الشرح مناسب لطلاب وطالبات الصف الرابع الابتدائي وفق المنهج السعودي، ويساعد على بناء أساس قوي في فهم الأعداد والقيمة المنزلية والاستعداد للاختبارات.\n\n👍 إذا استفدت من الفيديو، لا تنسَ الاشتراك في قناة الهَدَّاف وتفعيل 🔔 التنبيهات ليصلك كل جديد من شروحات المنهج السعودي.\n\n#رياضيات_رابع_ابتدائي #ال��يمة_المنزلية #مئات_الألوف #رابع_ابتدائي #رياضيات #الفصل_الأول #1448هـ #المنهج_السعودي #شرح_رياضيات #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "math-elem",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "شرح القيمة المنزلية ضمن مئات الألوف",
    "youtubeId": "zJVro_SvfDE",
    "youtubeUrl": "https://www.youtube.com/watch?v=zJVro_SvfDE",
    "thumbnailUrl": "https://i.ytimg.com/vi/zJVro_SvfDE/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 940,
    "likesCount": 94,
    "createdAt": "2026-08-25T06:04:49Z"
  },
  {
    "id": "yt_uwTdnirZEXk",
    "title": "شرح التصنيف وفق خاصية واحدة | رياضيات اولى  ابتدائى الفصل الأول 1448هـ | الدرس الأول",
    "description": "في هذا الفيديو نقدم شرحًا مبسطًا لدرس التصنيف وفق خاصية واحدة في مادة الرياضيات للصف الأول الابتدائي، الفصل الدراسي الأول 1448هـ.\n\n���� ماذا سنتعلم في الدرس؟\n\n- معنى التصنيف بطريقة سهلة ومبسطة.\n- تصنيف الأشياء وفق خاصية واحدة.\n- التصنيف حسب اللون.\n- التصنيف حسب الشكل.\n- التصنيف حسب الحجم.\n- تطبيقات وأمثلة تساعد الطالب على فهم الدرس.\n\n🎯 الشرح مناسب لطلاب وطالبات الصف الأول الابتدائي وفق المنهج السعودي، ويساعد على تأسيس مهارات التفكير الرياضي والتصنيف بطريقة ممتعة وسهلة.\n\n👍 إذا أعجبك الفيديو، لا تنسَ الاشتراك في قناة الهَدَّاف وتفعيل 🔔 التنبيهات ليصلك المزيد من شروحات الرياضيات والمواد الدراسية.\n\n#رياضيات_أول_ابتدائي #التصنيف #التصنيف_وفق_خاصية_واحدة #أول_ابتدائي #رياضيات #الفصل_الأول #1448هـ #المنهج_السعودي #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 1,
    "subjectId": "math-elem",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "شرح التصنيف وفق خاصية واحدة",
    "youtubeId": "uwTdnirZEXk",
    "youtubeUrl": "https://www.youtube.com/watch?v=uwTdnirZEXk",
    "thumbnailUrl": "https://i.ytimg.com/vi/uwTdnirZEXk/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 920,
    "likesCount": 92,
    "createdAt": "2026-08-25T05:47:12Z"
  },
  {
    "id": "yt_TJg6Q_OCH2w",
    "title": "شرح الخطوات الاربع لحل المسألة | الرياضيات الصف الاول المتوس�� الفصل الأول 1448هـ | الدرس الأول",
    "description": "📚 شرح الخطوات الأربع لحل المسألة | الرياضيات الصف الأول المتوسط | الفصل الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو نقدم شرحًا مبسطًا ومتكاملًا لدرس الخطوات الأربع لحل المسألة من مادة الرياضيات للصف الأول المتوسط، الفصل الدراسي الأول 1448هـ، مع توضيح كيفية التعامل مع المسائل الرياضية والوصول إلى الحل بطريقة منظمة.\n\n🎯 في هذا الدرس سنتعلم:\n\n- فهم المسألة وتحديد المعطيات والمطلوب.\n- التخطيط لحل المسألة واختيار الاستراتيجية المناسبة.\n- تنفيذ خطة الحل بطريقة صحيحة.\n- التحقق من صحة الحل والإجابة.\n- تطبيق الخطوات الأربع على أمثلة متنوعة.\n\n👨‍🏫 الشرح مناسب لطلاب وطالبات الأول المتوسط وفق المنهج السعودي، ويساعد على تأسيس مهارة مهمة في حل المسائل الرياضية والاستعداد للاختبارات.\n\n🔔 اشترك في قناة الهَدَّاف وفعل التنبيهات ليصلك المزيد من شروحات ودروس المنهج السعودي.\n\n#رياضيات_اول_متوسط #الخطوات_الأربع_لحل_المسألة #اول_متوسط #رياضيات #الفصل_الأول #1448هـ #المنهج_السعودي #شرح_رياضيات #الهَدَّاف",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 1,
    "subjectId": "math-mid",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "شرح الخطوات الاربع لحل المسألة",
    "youtubeId": "TJg6Q_OCH2w",
    "youtubeUrl": "https://www.youtube.com/watch?v=TJg6Q_OCH2w",
    "thumbnailUrl": "https://i.ytimg.com/vi/TJg6Q_OCH2w/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 900,
    "likesCount": 90,
    "createdAt": "2026-08-25T05:24:21Z"
  },
  {
    "id": "yt_EQnXb6LpeVo",
    "title": "شرح الخطوات الاربع لحل المسألة | رياضيات سادس ابتدائى الفصل الأول 1448هـ | الدرس الأول",
    "description": "📚 شرح الخطوات الأربع لحل المسألة | رياضيات سادس ابتدائي الفصل الأول 1448هـ\n\nفي هذا الفيديو نقدم شرحًا مبسطًا وواضحًا لدرس الخطوات الأربع لحل المسألة في مادة الرياضيات للصف السادس الابتدائي، الفصل الدراسي الأول 1448هـ.\n\n🎯 سنتعلم معًا كيفية استخدام الخطوات الأربع لحل المسائل الرياضية بطريقة منظمة وسهلة، مع توضيح طريقة فهم المسألة والوصول إلى الحل الصحيح.\n\n📌 محتوى الفيديو:\n\n- فه�� المسألة وتحديد المطلوب.\n- التخطيط للحل واختيار الاستراتيجية المناسبة.\n- تنفيذ خطة الحل.\n- التحقق من صحة الإجابة.\n- تطبيق الخطوات على أمثلة ومسائل متنوعة.\n\n👨‍🏫 الشرح مناسب لطلاب سادس ابتدائي ويساعد على فهم الدرس والاستعداد للاختبارات.\n\n👍 إذا استفدت من الفيديو، لا تنسَ الاشتراك في القناة وتفعيل 🔔 التنبيهات ليصلك كل جديد من شروحات الهَدَّاف التعليمية.\n\n#رياضيات_سادس_ابتدائي #الخطوات_الأربع_لحل_المسألة #سادس_ابتدائي #رياضيات #الفصل_الأول #1448هـ #المنهج_السعودي #شرح_رياضيات #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 6,
    "subjectId": "math-elem",
    "subjectName": "الرياضيات",
    "term": 1,
    "unitTitle": "شرح الخطوات الاربع لحل المسألة",
    "youtubeId": "EQnXb6LpeVo",
    "youtubeUrl": "https://www.youtube.com/watch?v=EQnXb6LpeVo",
    "thumbnailUrl": "https://i.ytimg.com/vi/EQnXb6LpeVo/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 880,
    "likesCount": 88,
    "createdAt": "2026-08-25T05:01:03Z"
  },
  {
    "id": "yt_01rgcLqB5dY",
    "title": "شرح المخلوقات الحية | علوم اولى ابتدائي الفصل الأول 1448هـ | الدرس الأول",
    "description": "🌱 شرح المخلوقات الحية | علوم أول ابتدائي الفصل الدراسي الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو من منصة الهَدَّاف التعليمية نقدم شرحًا بسيطًا وممتعًا لدرس المخلوقات الحية في مادة العلوم للصف الأول الابتدائي، وفق المنهج السعودي 1448هـ.\n\n🎯 في هذا الدرس سنتعرف على:\n• ما المقصود بالمخلوقات الحية؟\n• ما الذي يميز المخلوقات الحية؟\n• أمثلة على المخلوقات الحية من حولنا.\n• الفرق بين المخلوقات الحية والأشياء غير الحية.\n• كيف تنمو المخلوقات الحية وتتغير؟\n• أمثلة وتوضيحات تساعد الطالب على فهم الدرس بسهولة.\n\n📚 الفيديو مناسب لطلاب وطالبات الصف الأول الابتدائي – علوم – الفصل الدراسي الأول.\n\n⭐ لا تنسَ الاشتراك في قناة الهَدَّاف وتفعيل 🔔 الجرس لمتابعة المزيد من الشروحات التعليمية المبسطة.\n\n#الهَدَّاف #علوم_اول_ابتدائي #المخلوقات_الحية #علوم #اول_ابتدائي #الفصل_الدراسي_الأول #المنهج_السعودي #شرح_علوم",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 1,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "شرح المخلوقات الحية",
    "youtubeId": "01rgcLqB5dY",
    "youtubeUrl": "https://www.youtube.com/watch?v=01rgcLqB5dY",
    "thumbnailUrl": "https://i.ytimg.com/vi/01rgcLqB5dY/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 860,
    "likesCount": 86,
    "createdAt": "2026-08-24T20:31:43Z"
  },
  {
    "id": "yt_RjfnNAW_qcc",
    "title": "شرح الخلايا | علوم رابع ابتدائي الفصل الأول 1448هـ | الدرس الأول",
    "description": "🔬 شرح الخلايا | علوم رابع ابتدائي الفصل الدراسي الأول 1448هـ | الدرس الأول\n\nفي هذا الفيديو من منصة الهَدَّاف التعليمية نقدم شرحًا مبسطًا وممتعًا لدرس الخلايا في مادة العلوم للصف الرابع الابتدائي، وفق المنهج السعودي 1448هـ.\n\n🎯 في هذا الدرس سنتعرف على:\n• ما المقصود بالخلية؟\n• ما أنواع الخلايا؟\n• كيف تختلف الخلايا عن بعضها؟\n• أجزاء الخلية ووظائفها.\n• الفرق بين الخلية النباتية والخلية الحيوانية.\n• أمثلة وتوضيحات تساعد على فهم الدرس وتثبيت المعلومات.\n\n📚 الفيديو مناسب لطلاب وطالبات الصف الرابع الابتدائي – علوم – الفصل الدراسي الأول.\n\n⭐ إذا أعجبك الشرح، لا تنسَ الاشتراك في القناة وتفعيل 🔔 الجرس ليصلك كل جديد م�� دروس العلوم.\n\n#الهَدَّاف #علوم_رابع_ابتدائي #الخلايا #علوم #رابع_ابتدائي #الفصل_الدراسي_الأول #المنهج_السعودي #علوم_رابع #شرح_علوم",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 4,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "شرح الخلايا",
    "youtubeId": "RjfnNAW_qcc",
    "youtubeUrl": "https://www.youtube.com/watch?v=RjfnNAW_qcc",
    "thumbnailUrl": "https://i.ytimg.com/vi/RjfnNAW_qcc/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 840,
    "likesCount": 84,
    "createdAt": "2026-08-24T20:16:20Z"
  },
  {
    "id": "yt_EDndEdtcpZQ",
    "title": "شرح العلم وعملياته | علوم اولى متوسط الفصل الأول 1448هـ | الدرس الأول",
    "description": "في هذا الفيديو 📚🔬 نشرح درس العلم وعملياته لمادة العلوم للصف الأول المتوسط بطريقة سهلة ومبسطة، مع توضيح أهم المفاهيم والأفكار التي يحتاجها الطالب لفهم الدرس والاستعداد للاختبارات.\n\n🎯 في هذا الدرس سنتعرف على:\n• ما المقصود بالعلم؟\n• كيف يستخدم العلماء عمليات العلم؟\n• أهم مهارات وعمليات العلم.\n• الملاحظة والاستنتاج والتنبؤ.\n• القياس وجمع البيانات وتحليلها.\n• أهمية العلم وعملياته في حياتنا اليومية.\n• أمثلة وتوضيحات تساعدك على فهم الدرس وتثبيت المعلومات.\n\n📝 مناسب لـ:\nطلاب وطالبات الصف الأول المتوسط – مادة العلوم – المنهج السعودي.\n\n⭐ إذا استفدت من الفيديو لا تنسَ الاشتراك في قناة الهَدَّاف وتفعيل 🔔 الجرس ليصلك كل جديد من الشروحات التعليمية.\n\n#الهَدَّاف #علوم #اول_متوسط #العلوم #العلم_وعملياته #اولى_متوسط #المنهج_السعودي #علوم_اول_متوسط #شرح_علوم #قدرات_كمي #الصف_السادس #ثاني_متوسط",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 6,
    "subjectId": "science-mid",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "شرح العلم وعملياته",
    "youtubeId": "EDndEdtcpZQ",
    "youtubeUrl": "https://www.youtube.com/watch?v=EDndEdtcpZQ",
    "thumbnailUrl": "https://i.ytimg.com/vi/EDndEdtcpZQ/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 820,
    "likesCount": 82,
    "createdAt": "2026-08-24T19:20:21Z"
  },
  {
    "id": "yt_Zz3bNmnq6Q8",
    "title": "شرح نظرية الخلية | علوم سادس ابتدائي الفصل الأول 1448هـ | الدرس الأول",
    "description": "شرح نظرية الخلية | علوم سادس ابتدائي الفصل الأول 1448هـ\n\nفي هذا الفيديو نشرح الدرس الأول: نظرية الخلية من الفصل الأول: الخلايا في مادة العلوم للصف السادس الابتدائي – الفصل الدراسي الأول 1448هـ.\n\n📚 سنتعرف في الدرس على:\n• ما المقصود بالخلية؟\n• كيف تم اكتشاف الخلايا؟\n• ما نظرية الخلية؟\n• أهم العلماء الذين ساهموا في تطوير نظرية الخلية.\n• أهم أفكار نظرية الخلية بطريقة سهلة ومبسطة.\n• أمثلة وتوضيحات تساعدك على فهم الدرس وتثبيت المعلومات.\n\n🎯 هذا الشرح مناسب لطلاب وطالبات الصف السادس الابتدائي ويساعدك على فهم درس نظرية الخلية والاستعداد للاختبارات.\n\n📖 المادة: العلوم\n🎓 الصف: السادس الابتدائي\n📚 الفصل الدراسي: الأول\n📌 الفصل: الأول – الخلايا\n📝 الدرس: الأول – نظرية الخلية\n📅 المنهج: 1448هـ\n\nاشترك في القناة وفعل 🔔 التنبيهات ليصلك كل جديد من شروحات الهَدَّاف التعليمية.\n\nإذا استفدت من الشرح، لا تنسَ 👍 الإعجاب بالفيديو ومشاركته مع زملائك.\n\n#نظرية_الخلية #علوم_سادس #سادس_ابتدائي #علوم #الصف_السادس #الهَدَّاف",
    "country": "sa",
    "stage": "elementary",
    "gradeNumber": 6,
    "subjectId": "science-elem",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "شرح نظرية الخلية",
    "youtubeId": "Zz3bNmnq6Q8",
    "youtubeUrl": "https://www.youtube.com/watch?v=Zz3bNmnq6Q8",
    "thumbnailUrl": "https://i.ytimg.com/vi/Zz3bNmnq6Q8/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 800,
    "likesCount": 80,
    "createdAt": "2026-08-24T19:06:26Z"
  },
  {
    "id": "yt_hvDrKKdzAxM",
    "title": "شرح درس أسلوب العلم | علوم ثاني متوسط - الفصل الأول (المحاضرة 1)",
    "description": "في هذا الفيديو: شرح تفصيلي ومبسط للدرس الأول (أسلوب العلم) من الفصل الأول (طبيعة العلم) لمادة العلوم الصف الثاني المتوسط - الفصل الدراسي الأول (المنهج السعودي).\n#قدرات_كمي \n​اشترك في القناة ليصلك شرح باقي الدروس أولاً بأول.\n​#علوم_ثاني_متوسط #شرح_علوم #أسلوب_العلم #منهج_سعودي #ثاني_متوسط",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "science-mid",
    "subjectName": "العلوم",
    "term": 1,
    "unitTitle": "شرح درس أسلوب العلم",
    "youtubeId": "hvDrKKdzAxM",
    "youtubeUrl": "https://www.youtube.com/watch?v=hvDrKKdzAxM",
    "thumbnailUrl": "https://i.ytimg.com/vi/hvDrKKdzAxM/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 780,
    "likesCount": 78,
    "createdAt": "2026-08-24T07:36:08Z"
  },
  {
    "id": "yt_sDCt5JsQQik",
    "title": "شرح لغتي ثاني متوسط | الوحدة الأولى (مدخل الوحدة) | الفصل الدراسي الأول 1448هـ",
    "description": "في هذه المحاضرة الأولى من مادة \"لغتي الخالدة\" للصف الثاني المتوسط (الفصل الدراسي الأول)، نقدم شرحاً مبسطاً وشاملاً لدروس الوحدة الأولى.\n​نتعلم في هذا الدرس:\n​��رح مدخل الوحدة الأولى وأهدافها الأساسية.\n​قراءة وتحليل نص الانطلاق وتوضيح معاني المفردات الجديدة.\n​حل تدريبات الكتاب وتطبيقات لغوية بأسلوب سهل.\n​استخراج القواعد النحوية والإملائية المستهدفة.\n​هذا الفيديو مصمم خصيصاً لمساعدة طلاب الصف الثاني المتوسط في السعودية على التأسيس القوي في مادة لغتي وتحقيق أعلى الدرجات.",
    "country": "sa",
    "stage": "middle",
    "gradeNumber": 2,
    "subjectId": "arabic-mid",
    "subjectName": "لغتي الخالدة",
    "term": 1,
    "unitTitle": "شرح لغتي ثاني متوسط",
    "youtubeId": "sDCt5JsQQik",
    "youtubeUrl": "https://www.youtube.com/watch?v=sDCt5JsQQik",
    "thumbnailUrl": "https://i.ytimg.com/vi/sDCt5JsQQik/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 760,
    "likesCount": 76,
    "createdAt": "2026-08-24T06:47:31Z"
  },
  {
    "id": "yt_aHXqxHw1Lic",
    "title": "الدرس الأول: الضوء وطاقة الكم💡 كيمياء ثانوي سعودي | شرح مبسط وأمثلة وتطبيقات 📚",
    "description": "في هذه المحاضرة الأولى من الفصل الأول لمادة الكيمياء لطلاب المرحلة الثانوية في السعودية، يقدم الأستاذ محمد إبراهيم عبر قناة الهداف التعليمية شرحاً مبسطاً وعميقاً لدرس \"الضوء وطاقة الكم\".\n​سنتعرف في هذا الدرس على:\n​طبيعة الضوء الموجية والجسيمية.\n​مفهوم طاقة الكم وعلاقتها بالفوتونات.\n​المعادلات الأساسية لحساب طاقة الكم (E=hf و E=hc/λ).\n​أمثلة وتطبيقات عملية على قوانين طاقة الكم.\n​هذا الفيديو مصمم لمساعدة طلاب الكيمياء في الثانوية السعودية على تحقيق فهم عميق وتفوق مستمر في المادة.\n​🎥 اشترك في القناة لمتابعة باقي دروس الكيمياء للفصل الاول \n​",
    "country": "sa",
    "stage": "secondary",
    "gradeNumber": 1,
    "subjectId": "chem-sec",
    "subjectName": "الكيمياء",
    "term": 1,
    "unitTitle": "الدرس الأول: الضوء وطاقة الكم💡 كيمياء ثانوي سعودي",
    "youtubeId": "aHXqxHw1Lic",
    "youtubeUrl": "https://www.youtube.com/watch?v=aHXqxHw1Lic",
    "thumbnailUrl": "https://i.ytimg.com/vi/aHXqxHw1Lic/hqdefault.jpg",
    "duration": "18:00",
    "viewsCount": 740,
    "likesCount": 74,
    "createdAt": "2026-08-24T06:23:13Z"
  }
];

// ==========================================
// STANDALONE QUIZZES
// ==========================================
export const STANDALONE_QUIZZES: Quiz[] = [];

export const FAQS = [
  {
    question: 'هل منصة الهَدَّاف تغطي كافة المناهج العربية؟',
    answer: 'نعم، تدعم منصة الهَدَّاف المناهج الرسمية في المملكة العربية السعودية، جمهورية مصر العربية، الإمارات، الكويت، الأردن، وكافة الدول العربية.'
  },
  {
    question: 'كيف يتم ربط حسابي بالمنهج الخاص ببلدي؟',
    answer: 'عند إنشاء حسابك على المنصة تختار دولتك ومرحلتك الدراسية، ليتم توجيهك تلقائياً وبشكل مباشر لكافة مقررات ودروس واختبارات بلدك.'
  },
  {
    question: 'هل الشروحات والملخصات مجانية؟',
    answer: 'نعم، تقدم منصة الهَدَّاف كافة شروحات الفيديو والملخصات والاختبارات التفاعلية مجاناً لجميع الطلاب والمعلمين.'
  },
  {
    question: 'كيف يتم إضافة وتعديل المناهج والدروس؟',
    answer: 'يمتلك المشرف صلاحية الوصول للوحة التحكم الشاملة لجميع المناهج العربية لإضافة وتعديل ومزامنة الدروس والاختبارات بمرونة تامة.'
  }
];